INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00001', 'Phường Phúc Xá', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00004', 'Phường Trúc Bạch', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00006', 'Phường Vĩnh Phúc', 'Vinh Phuc Commune', 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00007', 'Phường Cống Vị', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00008', 'Phường Liễu Giai', 'Lieu Giai Commune', 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00010', 'Phường Nguyễn Trung Trực', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00013', 'Phường Quán Thánh', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00016', 'Phường Ngọc Hà', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00019', 'Phường Điện Biên', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00022', 'Phường Đội Cấn', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00025', 'Phường Ngọc Khánh', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00028', 'Phường Kim Mã', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00031', 'Phường Giảng Võ', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00034', 'Phường Thành Công', NULL, 'Phường', '1');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00037', 'Phường Phúc Tân', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00040', 'Phường Đồng Xuân', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00043', 'Phường Hàng Mã', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00046', 'Phường Hàng Buồm', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00049', 'Phường Hàng Đào', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00052', 'Phường Hàng Bồ', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00055', 'Phường Cửa Đông', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00058', 'Phường Lý Thái Tổ', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00061', 'Phường Hàng Bạc', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00064', 'Phường Hàng Gai', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00067', 'Phường Chương Dương', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00070', 'Phường Hàng Trống', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00073', 'Phường Cửa Nam', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00076', 'Phường Hàng Bông', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00079', 'Phường Tràng Tiền', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00082', 'Phường Trần Hưng Đạo', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00085', 'Phường Phan Chu Trinh', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00088', 'Phường Hàng Bài', NULL, 'Phường', '2');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00091', 'Phường Phú Thượng', NULL, 'Phường', '3');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00094', 'Phường Nhật Tân', NULL, 'Phường', '3');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00097', 'Phường Tứ Liên', NULL, 'Phường', '3');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00100', 'Phường Quảng An', NULL, 'Phường', '3');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00103', 'Phường Xuân La', NULL, 'Phường', '3');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00106', 'Phường Yên Phụ', NULL, 'Phường', '3');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00109', 'Phường Bưởi', NULL, 'Phường', '3');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00112', 'Phường Thụy Khuê', NULL, 'Phường', '3');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00115', 'Phường Thượng Thanh', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00118', 'Phường Ngọc Thụy', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00121', 'Phường Giang Biên', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00124', 'Phường Đức Giang', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00127', 'Phường Việt Hưng', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00130', 'Phường Gia Thụy', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00133', 'Phường Ngọc Lâm', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00136', 'Phường Phúc Lợi', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00139', 'Phường Bồ Đề', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00142', 'Phường Sài Đồng', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00145', 'Phường Long Biên', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00148', 'Phường Thạch Bàn', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00151', 'Phường Phúc Đồng', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00154', 'Phường Cự Khối', NULL, 'Phường', '4');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00157', 'Phường Nghĩa Đô', NULL, 'Phường', '5');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00160', 'Phường Nghĩa Tân', NULL, 'Phường', '5');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00163', 'Phường Mai Dịch', NULL, 'Phường', '5');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00166', 'Phường Dịch Vọng', NULL, 'Phường', '5');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00167', 'Phường Dịch Vọng Hậu', 'Dich Vong Hau Commune', 'Phường', '5');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00169', 'Phường Quan Hoa', NULL, 'Phường', '5');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00172', 'Phường Yên Hoà', NULL, 'Phường', '5');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00175', 'Phường Trung Hoà', NULL, 'Phường', '5');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00178', 'Phường Cát Linh', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00181', 'Phường Văn Miếu', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00184', 'Phường Quốc Tử Giám', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00187', 'Phường Láng Thượng', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00190', 'Phường Ô Chợ Dừa', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00193', 'Phường Văn Chương', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00196', 'Phường Hàng Bột', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00199', 'Phường Láng Hạ', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00202', 'Phường Khâm Thiên', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00205', 'Phường Thổ Quan', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00208', 'Phường Nam Đồng', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00211', 'Phường Trung Phụng', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00214', 'Phường Quang Trung', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00217', 'Phường Trung Liệt', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00220', 'Phường Phương Liên', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00223', 'Phường Thịnh Quang', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00226', 'Phường Trung Tự', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00229', 'Phường Kim Liên', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00232', 'Phường Phương Mai', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00235', 'Phường Ngã Tư Sở', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00238', 'Phường Khương Thượng', NULL, 'Phường', '6');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00241', 'Phường Nguyễn Du', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00244', 'Phường Bạch Đằng', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00247', 'Phường Phạm Đình Hổ', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00256', 'Phường Lê Đại Hành', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00259', 'Phường Đồng Nhân', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00262', 'Phường Phố Huế', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00265', 'Phường Đống Mác', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00268', 'Phường Thanh Lương', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00271', 'Phường Thanh Nhàn', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00274', 'Phường Cầu Dền', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00277', 'Phường Bách Khoa', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00280', 'Phường Đồng Tâm', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00283', 'Phường Vĩnh Tuy', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00286', 'Phường Bạch Mai', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00289', 'Phường Quỳnh Mai', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00292', 'Phường Quỳnh Lôi', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00295', 'Phường Minh Khai', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00298', 'Phường Trương Định', NULL, 'Phường', '7');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00301', 'Phường Thanh Trì', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00304', 'Phường Vĩnh Hưng', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00307', 'Phường Định Công', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00310', 'Phường Mai Động', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00313', 'Phường Tương Mai', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00316', 'Phường Đại Kim', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00319', 'Phường Tân Mai', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00322', 'Phường Hoàng Văn Thụ', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00325', 'Phường Giáp Bát', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00328', 'Phường Lĩnh Nam', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00331', 'Phường Thịnh Liệt', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00334', 'Phường Trần Phú', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00337', 'Phường Hoàng Liệt', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00340', 'Phường Yên Sở', NULL, 'Phường', '8');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00343', 'Phường Nhân Chính', NULL, 'Phường', '9');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00346', 'Phường Thượng Đình', NULL, 'Phường', '9');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00349', 'Phường Khương Trung', NULL, 'Phường', '9');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00352', 'Phường Khương Mai', NULL, 'Phường', '9');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00355', 'Phường Thanh Xuân Trung', NULL, 'Phường', '9');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00358', 'Phường Phương Liệt', NULL, 'Phường', '9');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00361', 'Phường Hạ Đình', NULL, 'Phường', '9');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00364', 'Phường Khương Đình', NULL, 'Phường', '9');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00367', 'Phường Thanh Xuân Bắc', NULL, 'Phường', '9');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00370', 'Phường Thanh Xuân Nam', NULL, 'Phường', '9');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00373', 'Phường Kim Giang', NULL, 'Phường', '9');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00376', 'Thị trấn Sóc Sơn', NULL, 'Thị trấn', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00379', 'Xã Bắc Sơn', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00382', 'Xã Minh Trí', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00385', 'Xã Hồng Kỳ', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00388', 'Xã Nam Sơn', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00391', 'Xã Trung Giã', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00394', 'Xã Tân Hưng', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00397', 'Xã Minh Phú', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00400', 'Xã Phù Linh', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00403', 'Xã Bắc Phú', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00406', 'Xã Tân Minh', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00409', 'Xã Quang Tiến', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00412', 'Xã Hiền Ninh', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00415', 'Xã Tân Dân', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00418', 'Xã Tiên Dược', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00421', 'Xã Việt Long', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00424', 'Xã Xuân Giang', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00427', 'Xã Mai Đình', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00430', 'Xã Đức Hoà', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00433', 'Xã Thanh Xuân', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00436', 'Xã Đông Xuân', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00439', 'Xã Kim Lũ', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00442', 'Xã Phú Cường', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00445', 'Xã Phú Minh', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00448', 'Xã Phù Lỗ', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00451', 'Xã Xuân Thu', NULL, 'Xã', '16');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00454', 'Thị trấn Đông Anh', NULL, 'Thị trấn', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00457', 'Xã Xuân Nộn', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00460', 'Xã Thuỵ Lâm', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00463', 'Xã Bắc Hồng', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00466', 'Xã Nguyên Khê', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00469', 'Xã Nam Hồng', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00472', 'Xã Tiên Dương', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00475', 'Xã Vân Hà', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00478', 'Xã Uy Nỗ', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00481', 'Xã Vân Nội', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00484', 'Xã Liên Hà', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00487', 'Xã Việt Hùng', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00490', 'Xã Kim Nỗ', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00493', 'Xã Kim Chung', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00496', 'Xã Dục Tú', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00499', 'Xã Đại Mạch', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00502', 'Xã Vĩnh Ngọc', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00505', 'Xã Cổ Loa', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00508', 'Xã Hải Bối', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00511', 'Xã Xuân Canh', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00514', 'Xã Võng La', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00517', 'Xã Tàm Xá', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00520', 'Xã Mai Lâm', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00523', 'Xã Đông Hội', NULL, 'Xã', '17');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00526', 'Thị trấn Yên Viên', NULL, 'Thị trấn', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00529', 'Xã Yên Thường', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00532', 'Xã Yên Viên', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00535', 'Xã Ninh Hiệp', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00538', 'Xã Đình Xuyên', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00541', 'Xã Dương Hà', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00544', 'Xã Phù Đổng', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00547', 'Xã Trung Mầu', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00550', 'Xã Lệ Chi', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00553', 'Xã Cổ Bi', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00556', 'Xã Đặng Xá', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00559', 'Xã Phú Thị', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00562', 'Xã Kim Sơn', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00565', 'Thị trấn Trâu Quỳ', 'Trau Quy Commune', 'Thị trấn', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00568', 'Xã Dương Quang', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00571', 'Xã Dương Xá', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00574', 'Xã Đông Dư', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00577', 'Xã Đa Tốn', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00580', 'Xã Kiêu Kỵ', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00583', 'Xã Bát Tràng', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00586', 'Xã Kim Lan', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00589', 'Xã Văn Đức', NULL, 'Xã', '18');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00592', 'Phường Cầu Diễn', NULL, 'Phường', '19');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00622', 'Phường Xuân Phương', NULL, 'Phường', '19');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00623', 'Phường Phương Canh', NULL, 'Phường', '19');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00625', 'Phường Mỹ Đình 1', NULL, 'Phường', '19');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00626', 'Phường Mỹ Đình 2', NULL, 'Phường', '19');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00628', 'Phường Tây Mỗ', NULL, 'Phường', '19');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00631', 'Phường Mễ Trì', NULL, 'Phường', '19');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00632', 'Phường Phú Đô', NULL, 'Phường', '19');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00634', 'Phường Đại Mỗ', NULL, 'Phường', '19');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00637', 'Phường Trung Văn', NULL, 'Phường', '19');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00640', 'Thị trấn Văn Điển', NULL, 'Thị trấn', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00643', 'Xã Tân Triều', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00646', 'Xã Thanh Liệt', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00649', 'Xã Tả Thanh Oai', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00652', 'Xã Hữu Hoà', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00655', 'Xã Tam Hiệp', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00658', 'Xã Tứ Hiệp', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00661', 'Xã Yên Mỹ', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00664', 'Xã Vĩnh Quỳnh', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00667', 'Xã Ngũ Hiệp', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00670', 'Xã Duyên Hà', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00673', 'Xã Ngọc Hồi', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00676', 'Xã Vạn Phúc', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00679', 'Xã Đại áng', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00682', 'Xã Liên Ninh', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00685', 'Xã Đông Mỹ', NULL, 'Xã', '20');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00595', 'Phường Thượng Cát', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00598', 'Phường Liên Mạc', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00601', 'Phường Đông Ngạc', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00602', 'Phường Đức Thắng', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00604', 'Phường Thụy Phương', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00607', 'Phường Tây Tựu', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00610', 'Phường Xuân Đỉnh', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00611', 'Phường Xuân Tảo', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00613', 'Phường Minh Khai', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00616', 'Phường Cổ Nhuế 1', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00617', 'Phường Cổ Nhuế 2', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00619', 'Phường Phú Diễn', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00620', 'Phường Phúc Diễn', NULL, 'Phường', '21');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('08973', 'Thị trấn Chi Đông', NULL, 'Thị trấn', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('08974', 'Xã Đại Thịnh', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('08977', 'Xã Kim Hoa', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('08980', 'Xã Thạch Đà', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('08983', 'Xã Tiến Thắng', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('08986', 'Xã Tự Lập', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('08989', 'Thị trấn Quang Minh', NULL, 'Thị trấn', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('08992', 'Xã Thanh Lâm', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('08995', 'Xã Tam Đồng', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('08998', 'Xã Liên Mạc', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09001', 'Xã Vạn Yên', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09004', 'Xã Chu Phan', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09007', 'Xã Tiến Thịnh', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09010', 'Xã Mê Linh', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09013', 'Xã Văn Khê', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09016', 'Xã Hoàng Kim', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09019', 'Xã Tiền Phong', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09022', 'Xã Tráng Việt', NULL, 'Xã', '250');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09538', 'Phường Nguyễn Trãi', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09541', 'Phường Mộ Lao', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09542', 'Phường Văn Quán', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09544', 'Phường Vạn Phúc', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09547', 'Phường Yết Kiêu', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09550', 'Phường Quang Trung', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09551', 'Phường La Khê', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09552', 'Phường Phú La', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09553', 'Phường Phúc La', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09556', 'Phường Hà Cầu', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09562', 'Phường Yên Nghĩa', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09565', 'Phường Kiến Hưng', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09568', 'Phường Phú Lãm', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09571', 'Phường Phú Lương', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09886', 'Phường Dương Nội', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10117', 'Phường Đồng Mai', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10123', 'Phường Biên Giang', NULL, 'Phường', '268');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09574', 'Phường Lê Lợi', NULL, 'Phường', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09577', 'Phường Phú Thịnh', NULL, 'Phường', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09580', 'Phường Ngô Quyền', NULL, 'Phường', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09583', 'Phường Quang Trung', NULL, 'Phường', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09586', 'Phường Sơn Lộc', NULL, 'Phường', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09589', 'Phường Xuân Khanh', NULL, 'Phường', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09592', 'Xã Đường Lâm', NULL, 'Xã', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09595', 'Phường Viên Sơn', NULL, 'Phường', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09598', 'Xã Xuân Sơn', NULL, 'Xã', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09601', 'Phường Trung Hưng', NULL, 'Phường', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09604', 'Xã Thanh Mỹ', NULL, 'Xã', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09607', 'Phường Trung Sơn Trầm', NULL, 'Phường', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09610', 'Xã Kim Sơn', NULL, 'Xã', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09613', 'Xã Sơn Đông', NULL, 'Xã', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09616', 'Xã Cổ Đông', NULL, 'Xã', '269');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09619', 'Thị trấn Tây Đằng', NULL, 'Thị trấn', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09625', 'Xã Phú Cường', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09628', 'Xã Cổ Đô', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09631', 'Xã Tản Hồng', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09634', 'Xã Vạn Thắng', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09637', 'Xã Châu Sơn', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09640', 'Xã Phong Vân', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09643', 'Xã Phú Đông', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09646', 'Xã Phú Phương', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09649', 'Xã Phú Châu', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09652', 'Xã Thái Hòa', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09655', 'Xã Đồng Thái', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09658', 'Xã Phú Sơn', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09661', 'Xã Minh Châu', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09664', 'Xã Vật Lại', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09667', 'Xã Chu Minh', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09670', 'Xã Tòng Bạt', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09673', 'Xã Cẩm Lĩnh', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09676', 'Xã Sơn Đà', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09679', 'Xã Đông Quang', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09682', 'Xã Tiên Phong', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09685', 'Xã Thụy An', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09688', 'Xã Cam Thượng', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09691', 'Xã Thuần Mỹ', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09694', 'Xã Tản Lĩnh', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09697', 'Xã Ba Trại', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09700', 'Xã Minh Quang', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09703', 'Xã Ba Vì', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09706', 'Xã Vân Hòa', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09709', 'Xã Yên Bài', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09712', 'Xã Khánh Thượng', NULL, 'Xã', '271');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09715', 'Thị trấn Phúc Thọ', NULL, 'Thị trấn', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09718', 'Xã Vân Hà', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09721', 'Xã Vân Phúc', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09724', 'Xã Vân Nam', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09727', 'Xã Xuân Đình', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09733', 'Xã Sen Phương', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09739', 'Xã Võng Xuyên', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09742', 'Xã Thọ Lộc', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09745', 'Xã Long Xuyên', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09748', 'Xã Thượng Cốc', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09751', 'Xã Hát Môn', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09754', 'Xã Tích Giang', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09757', 'Xã Thanh Đa', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09760', 'Xã Trạch Mỹ Lộc', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09763', 'Xã Phúc Hòa', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09766', 'Xã Ngọc Tảo', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09769', 'Xã Phụng Thượng', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09772', 'Xã Tam Thuấn', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09775', 'Xã Tam Hiệp', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09778', 'Xã Hiệp Thuận', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09781', 'Xã Liên Hiệp', NULL, 'Xã', '272');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09784', 'Thị trấn Phùng', NULL, 'Thị trấn', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09787', 'Xã Trung Châu', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09790', 'Xã Thọ An', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09793', 'Xã Thọ Xuân', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09796', 'Xã Hồng Hà', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09799', 'Xã Liên Hồng', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09802', 'Xã Liên Hà', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09805', 'Xã Hạ Mỗ', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09808', 'Xã Liên Trung', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09811', 'Xã Phương Đình', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09814', 'Xã Thượng Mỗ', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09817', 'Xã Tân Hội', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09820', 'Xã Tân Lập', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09823', 'Xã Đan Phượng', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09826', 'Xã Đồng Tháp', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09829', 'Xã Song Phượng', NULL, 'Xã', '273');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09832', 'Thị trấn Trạm Trôi', NULL, 'Thị trấn', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09835', 'Xã Đức Thượng', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09838', 'Xã Minh Khai', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09841', 'Xã Dương Liễu', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09844', 'Xã Di Trạch', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09847', 'Xã Đức Giang', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09850', 'Xã Cát Quế', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09853', 'Xã Kim Chung', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09856', 'Xã Yên Sở', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09859', 'Xã Sơn Đồng', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09862', 'Xã Vân Canh', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09865', 'Xã Đắc Sở', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09868', 'Xã Lại Yên', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09871', 'Xã Tiền Yên', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09874', 'Xã Song Phương', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09877', 'Xã An Khánh', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09880', 'Xã An Thượng', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09883', 'Xã Vân Côn', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09889', 'Xã La Phù', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09892', 'Xã Đông La', NULL, 'Xã', '274');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04939', 'Xã Đông Xuân', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09895', 'Thị trấn Quốc Oai', NULL, 'Thị trấn', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09898', 'Xã Sài Sơn', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09901', 'Xã Phượng Cách', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09904', 'Xã Yên Sơn', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09907', 'Xã Ngọc Liệp', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09910', 'Xã Ngọc Mỹ', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09913', 'Xã Liệp Tuyết', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09916', 'Xã Thạch Thán', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09919', 'Xã Đồng Quang', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09922', 'Xã Phú Cát', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09925', 'Xã Tuyết Nghĩa', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09928', 'Xã Nghĩa Hương', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09931', 'Xã Cộng Hòa', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09934', 'Xã Tân Phú', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09937', 'Xã Đại Thành', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09940', 'Xã Phú Mãn', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09943', 'Xã Cấn Hữu', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09946', 'Xã Tân Hòa', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09949', 'Xã Hòa Thạch', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09952', 'Xã Đông Yên', NULL, 'Xã', '275');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04927', 'Xã Yên Trung', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04930', 'Xã Yên Bình', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04936', 'Xã Tiến Xuân', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09955', 'Thị trấn Liên Quan', NULL, 'Thị trấn', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09958', 'Xã Đại Đồng', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09961', 'Xã Cẩm Yên', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09964', 'Xã Lại Thượng', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09967', 'Xã Phú Kim', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09970', 'Xã Hương Ngải', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09973', 'Xã Canh Nậu', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09976', 'Xã Kim Quan', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09979', 'Xã Dị Nậu', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09982', 'Xã Bình Yên', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09985', 'Xã Chàng Sơn', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09988', 'Xã Thạch Hoà', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09991', 'Xã Cần Kiệm', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09994', 'Xã Hữu Bằng', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('09997', 'Xã Phùng Xá', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10000', 'Xã Tân Xã', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10003', 'Xã Thạch Xá', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10006', 'Xã Bình Phú', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10009', 'Xã Hạ Bằng', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10012', 'Xã Đồng Trúc', NULL, 'Xã', '276');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10015', 'Thị trấn Chúc Sơn', NULL, 'Thị trấn', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10018', 'Thị trấn Xuân Mai', NULL, 'Thị trấn', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10021', 'Xã Phụng Châu', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10024', 'Xã Tiên Phương', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10027', 'Xã Đông Sơn', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10030', 'Xã Đông Phương Yên', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10033', 'Xã Phú Nghĩa', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10039', 'Xã Trường Yên', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10042', 'Xã Ngọc Hòa', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10045', 'Xã Thủy Xuân Tiên', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10048', 'Xã Thanh Bình', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10051', 'Xã Trung Hòa', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10054', 'Xã Đại Yên', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10057', 'Xã Thụy Hương', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10060', 'Xã Tốt Động', NULL, 'Xã', '277');