INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10063', 'Xã Lam Điền', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10066', 'Xã Tân Tiến', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10069', 'Xã Nam Phương Tiến', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10072', 'Xã Hợp Đồng', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10075', 'Xã Hoàng Văn Thụ', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10078', 'Xã Hoàng Diệu', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10081', 'Xã Hữu Văn', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10084', 'Xã Quảng Bị', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10087', 'Xã Mỹ Lương', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10090', 'Xã Thượng Vực', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10093', 'Xã Hồng Phong', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10096', 'Xã Đồng Phú', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10099', 'Xã Trần Phú', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10102', 'Xã Văn Võ', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10105', 'Xã Đồng Lạc', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10108', 'Xã Hòa Chính', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10111', 'Xã Phú Nam An', NULL, 'Xã', '277');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10114', 'Thị trấn Kim Bài', NULL, 'Thị trấn', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10120', 'Xã Cự Khê', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10126', 'Xã Bích Hòa', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10129', 'Xã Mỹ Hưng', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10132', 'Xã Cao Viên', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10135', 'Xã Bình Minh', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10138', 'Xã Tam Hưng', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10141', 'Xã Thanh Cao', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10144', 'Xã Thanh Thùy', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10147', 'Xã Thanh Mai', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10150', 'Xã Thanh Văn', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10153', 'Xã Đỗ Động', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10156', 'Xã Kim An', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10159', 'Xã Kim Thư', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10162', 'Xã Phương Trung', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10165', 'Xã Tân Ước', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10168', 'Xã Dân Hòa', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10171', 'Xã Liên Châu', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10174', 'Xã Cao Dương', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10177', 'Xã Xuân Dương', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10180', 'Xã Hồng Dương', NULL, 'Xã', '278');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10183', 'Thị trấn Thường Tín', NULL, 'Thị trấn', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10186', 'Xã Ninh Sở', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10189', 'Xã Nhị Khê', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10192', 'Xã Duyên Thái', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10195', 'Xã Khánh Hà', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10198', 'Xã Hòa Bình', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10201', 'Xã Văn Bình', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10204', 'Xã Hiền Giang', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10207', 'Xã Hồng Vân', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10210', 'Xã Vân Tảo', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10213', 'Xã Liên Phương', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10216', 'Xã Văn Phú', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10219', 'Xã Tự Nhiên', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10222', 'Xã Tiền Phong', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10225', 'Xã Hà Hồi', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10228', 'Xã Thư Phú', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10231', 'Xã Nguyễn Trãi', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10234', 'Xã Quất Động', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10237', 'Xã Chương Dương', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10240', 'Xã Tân Minh', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10243', 'Xã Lê Lợi', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10246', 'Xã Thắng Lợi', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10249', 'Xã Dũng Tiến', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10252', 'Xã Thống Nhất', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10255', 'Xã Nghiêm Xuyên', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10258', 'Xã Tô Hiệu', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10261', 'Xã Văn Tự', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10264', 'Xã Vạn Điểm', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10267', 'Xã Minh Cường', NULL, 'Xã', '279');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10270', 'Thị trấn Phú Minh', NULL, 'Thị trấn', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10273', 'Thị trấn Phú Xuyên', NULL, 'Thị trấn', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10276', 'Xã Hồng Minh', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10279', 'Xã Phượng Dực', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10282', 'Xã Nam Tiến', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10288', 'Xã Tri Trung', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10291', 'Xã Đại Thắng', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10294', 'Xã Phú Túc', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10297', 'Xã Văn Hoàng', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10300', 'Xã Hồng Thái', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10303', 'Xã Hoàng Long', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10306', 'Xã Quang Trung', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10309', 'Xã Nam Phong', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10312', 'Xã Nam Triều', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10315', 'Xã Tân Dân', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10318', 'Xã Sơn Hà', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10321', 'Xã Chuyên Mỹ', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10324', 'Xã Khai Thái', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10327', 'Xã Phúc Tiến', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10330', 'Xã Vân Từ', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10333', 'Xã Tri Thủy', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10336', 'Xã Đại Xuyên', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10339', 'Xã Phú Yên', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10342', 'Xã Bạch Hạ', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10345', 'Xã Quang Lãng', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10348', 'Xã Châu Can', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10351', 'Xã Minh Tân', NULL, 'Xã', '280');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10354', 'Thị trấn Vân Đình', NULL, 'Thị trấn', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10357', 'Xã Viên An', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10360', 'Xã Viên Nội', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10363', 'Xã Hoa Sơn', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10366', 'Xã Quảng Phú Cầu', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10369', 'Xã Trường Thịnh', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10372', 'Xã Cao Thành', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10375', 'Xã Liên Bạt', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10378', 'Xã Sơn Công', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10381', 'Xã Đồng Tiến', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10384', 'Xã Phương Tú', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10387', 'Xã Trung Tú', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10390', 'Xã Đồng Tân', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10393', 'Xã Tảo Dương Văn', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10396', 'Xã Vạn Thái', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10399', 'Xã Minh Đức', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10402', 'Xã Hòa Lâm', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10405', 'Xã Hòa Xá', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10408', 'Xã Trầm Lộng', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10411', 'Xã Kim Đường', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10414', 'Xã Hòa Nam', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10417', 'Xã Hòa Phú', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10420', 'Xã Đội Bình', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10423', 'Xã Đại Hùng', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10426', 'Xã Đông Lỗ', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10429', 'Xã Phù Lưu', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10432', 'Xã Đại Cường', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10435', 'Xã Lưu Hoàng', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10438', 'Xã Hồng Quang', NULL, 'Xã', '281');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10441', 'Thị trấn Đại Nghĩa', NULL, 'Thị trấn', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10444', 'Xã Đồng Tâm', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10447', 'Xã Thượng Lâm', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10450', 'Xã Tuy Lai', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10453', 'Xã Phúc Lâm', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10456', 'Xã Mỹ Thành', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10459', 'Xã Bột Xuyên', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10462', 'Xã An Mỹ', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10465', 'Xã Hồng Sơn', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10468', 'Xã Lê Thanh', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10471', 'Xã Xuy Xá', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10474', 'Xã Phùng Xá', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10477', 'Xã Phù Lưu Tế', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10480', 'Xã Đại Hưng', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10483', 'Xã Vạn Kim', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10486', 'Xã Đốc Tín', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10489', 'Xã Hương Sơn', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10492', 'Xã Hùng Tiến', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10495', 'Xã An Tiến', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10498', 'Xã Hợp Tiến', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10501', 'Xã Hợp Thanh', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('10504', 'Xã An Phú', NULL, 'Xã', '282');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00688', 'Phường Quang Trung', NULL, 'Phường', '24');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00691', 'Phường Trần Phú', NULL, 'Phường', '24');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00692', 'Phường Ngọc Hà', NULL, 'Phường', '24');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00694', 'Phường Nguyễn Trãi', NULL, 'Phường', '24');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00697', 'Phường Minh Khai', NULL, 'Phường', '24');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00700', 'Xã Ngọc Đường', NULL, 'Xã', '24');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00946', 'Xã Phương Độ', NULL, 'Xã', '24');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00949', 'Xã Phương Thiện', NULL, 'Xã', '24');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00712', 'Thị trấn Phó Bảng', NULL, 'Thị trấn', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00715', 'Xã Lũng Cú', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00718', 'Xã Má Lé', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00721', 'Thị trấn Đồng Văn', NULL, 'Thị trấn', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00724', 'Xã Lũng Táo', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00727', 'Xã Phố Là', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00730', 'Xã Thài Phìn Tủng', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00733', 'Xã Sủng Là', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00736', 'Xã Xà Phìn', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00739', 'Xã Tả Phìn', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00742', 'Xã Tả Lủng', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00745', 'Xã Phố Cáo', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00748', 'Xã Sính Lủng', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00751', 'Xã Sảng Tủng', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00754', 'Xã Lũng Thầu', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00757', 'Xã Hố Quáng Phìn', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00760', 'Xã Vần Chải', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00763', 'Xã Lũng Phìn', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00766', 'Xã Sủng Trái', NULL, 'Xã', '26');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00769', 'Thị trấn Mèo Vạc', NULL, 'Thị trấn', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00772', 'Xã Thượng Phùng', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00775', 'Xã Pải Lủng', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00778', 'Xã Xín Cái', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00781', 'Xã Pả Vi', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00784', 'Xã Giàng Chu Phìn', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00787', 'Xã Sủng Trà', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00790', 'Xã Sủng Máng', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00793', 'Xã Sơn Vĩ', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00796', 'Xã Tả Lủng', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00799', 'Xã Cán Chu Phìn', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00802', 'Xã Lũng Pù', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00805', 'Xã Lũng Chinh', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00808', 'Xã Tát Ngà', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00811', 'Xã Nậm Ban', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00814', 'Xã Khâu Vai', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00815', 'Xã Niêm Tòng', 'Niem Tong commune', 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00817', 'Xã Niêm Sơn', NULL, 'Xã', '27');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00820', 'Thị trấn Yên Minh', NULL, 'Thị trấn', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00823', 'Xã Thắng Mố', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00826', 'Xã Phú Lũng', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00829', 'Xã Sủng Tráng', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00832', 'Xã Bạch Đích', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00835', 'Xã Na Khê', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00838', 'Xã Sủng Thài', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00841', 'Xã Hữu Vinh', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00844', 'Xã Lao Và Chải', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00847', 'Xã Mậu Duệ', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00850', 'Xã Đông Minh', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00853', 'Xã Mậu Long', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00856', 'Xã Ngam La', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00859', 'Xã Ngọc Long', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00862', 'Xã Đường Thượng', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00865', 'Xã Lũng Hồ', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00868', 'Xã Du Tiến', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00871', 'Xã Du Già', NULL, 'Xã', '28');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00874', 'Thị trấn Tam Sơn', NULL, 'Thị trấn', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00877', 'Xã Bát Đại Sơn', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00880', 'Xã Nghĩa Thuận', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00883', 'Xã Cán Tỷ', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00886', 'Xã Cao Mã Pờ', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00889', 'Xã Thanh Vân', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00892', 'Xã Tùng Vài', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00895', 'Xã Đông Hà', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00898', 'Xã Quản Bạ', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00901', 'Xã Lùng Tám', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00904', 'Xã Quyết Tiến', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00907', 'Xã Tả Ván', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00910', 'Xã Thái An', NULL, 'Xã', '29');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00703', 'Xã Kim Thạch', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00706', 'Xã Phú Linh', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00709', 'Xã Kim Linh', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00913', 'Thị trấn Vị Xuyên', NULL, 'Thị trấn', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00916', 'Thị trấn Nông Trường Việt Lâm', NULL, 'Thị trấn', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00919', 'Xã Minh Tân', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00922', 'Xã Thuận Hoà', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00925', 'Xã Tùng Bá', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00928', 'Xã Thanh Thủy', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00931', 'Xã Thanh Đức', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00934', 'Xã Phong Quang', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00937', 'Xã Xín Chải', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00940', 'Xã Phương Tiến', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00943', 'Xã Lao Chải', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00952', 'Xã Cao Bồ', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00955', 'Xã Đạo Đức', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00958', 'Xã Thượng Sơn', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00961', 'Xã Linh Hồ', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00964', 'Xã Quảng Ngần', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00967', 'Xã Việt Lâm', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00970', 'Xã Ngọc Linh', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00973', 'Xã Ngọc Minh', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00976', 'Xã Bạch Ngọc', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00979', 'Xã Trung Thành', NULL, 'Xã', '30');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00982', 'Xã Minh Sơn', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00985', 'Xã Giáp Trung', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00988', 'Xã Yên Định', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00991', 'Thị trấn Yên Phú', NULL, 'Thị trấn', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00994', 'Xã Minh Ngọc', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('00997', 'Xã Yên Phong', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01000', 'Xã Lạc Nông', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01003', 'Xã Phú Nam', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01006', 'Xã Yên Cường', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01009', 'Xã Thượng Tân', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01012', 'Xã Đường Âm', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01015', 'Xã Đường Hồng', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01018', 'Xã Phiêng Luông', NULL, 'Xã', '31');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01021', 'Thị trấn Vinh Quang', NULL, 'Thị trấn', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01024', 'Xã Bản Máy', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01027', 'Xã Thàng Tín', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01030', 'Xã Thèn Chu Phìn', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01033', 'Xã Pố Lồ', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01036', 'Xã Bản Phùng', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01039', 'Xã Túng Sán', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01042', 'Xã Chiến Phố', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01045', 'Xã Đản Ván', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01048', 'Xã Tụ Nhân', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01051', 'Xã Tân Tiến', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01054', 'Xã Nàng Đôn', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01057', 'Xã Pờ Ly Ngài', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01060', 'Xã Sán Xả Hồ', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01063', 'Xã Bản Luốc', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01066', 'Xã Ngàm Đăng Vài', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01069', 'Xã Bản Nhùng', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01072', 'Xã Tả Sử Choóng', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01075', 'Xã Nậm Dịch', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01081', 'Xã Hồ Thầu', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01084', 'Xã Nam Sơn', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01087', 'Xã Nậm Tỵ', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01090', 'Xã Thông Nguyên', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01093', 'Xã Nậm Khòa', NULL, 'Xã', '32');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01096', 'Thị trấn Cốc Pài', NULL, 'Thị trấn', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01099', 'Xã Nàn Xỉn', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01102', 'Xã Bản Díu', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01105', 'Xã Chí Cà', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01108', 'Xã Xín Mần', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01114', 'Xã Thèn Phàng', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01117', 'Xã Trung Thịnh', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01120', 'Xã Pà Vầy Sủ', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01123', 'Xã Cốc Rế', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01126', 'Xã Thu Tà', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01129', 'Xã Nàn Ma', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01132', 'Xã Tả Nhìu', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01135', 'Xã Bản Ngò', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01138', 'Xã Chế Là', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01141', 'Xã Nấm Dẩn', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01144', 'Xã Quảng Nguyên', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01147', 'Xã Nà Chì', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01150', 'Xã Khuôn Lùng', NULL, 'Xã', '33');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01153', 'Thị trấn Việt Quang', NULL, 'Thị trấn', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01156', 'Thị trấn Vĩnh Tuy', NULL, 'Thị trấn', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01159', 'Xã Tân Lập', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01162', 'Xã Tân Thành', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01165', 'Xã Đồng Tiến', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01168', 'Xã Đồng Tâm', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01171', 'Xã Tân Quang', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01174', 'Xã Thượng Bình', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01177', 'Xã Hữu Sản', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01180', 'Xã Kim Ngọc', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01183', 'Xã Việt Vinh', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01186', 'Xã Bằng Hành', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01189', 'Xã Quang Minh', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01192', 'Xã Liên Hiệp', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01195', 'Xã Vô Điếm', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01198', 'Xã Việt Hồng', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01201', 'Xã Hùng An', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01204', 'Xã Đức Xuân', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01207', 'Xã Tiên Kiều', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01210', 'Xã Vĩnh Hảo', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01213', 'Xã Vĩnh Phúc', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01216', 'Xã Đồng Yên', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01219', 'Xã Đông Thành', NULL, 'Xã', '34');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01222', 'Xã Xuân Minh', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01225', 'Xã Tiên Nguyên', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01228', 'Xã Tân Nam', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01231', 'Xã Bản Rịa', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01234', 'Xã Yên Thành', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01237', 'Thị trấn Yên Bình', NULL, 'Thị trấn', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01240', 'Xã Tân Trịnh', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01243', 'Xã Tân Bắc', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01246', 'Xã Bằng Lang', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01249', 'Xã Yên Hà', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01252', 'Xã Hương Sơn', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01255', 'Xã Xuân Giang', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01258', 'Xã Nà Khương', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01261', 'Xã Tiên Yên', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01264', 'Xã Vĩ Thượng', NULL, 'Xã', '35');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01267', 'Phường Sông Hiến', NULL, 'Phường', '40');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01270', 'Phường Sông Bằng', NULL, 'Phường', '40');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01273', 'Phường Hợp Giang', NULL, 'Phường', '40');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01276', 'Phường Tân Giang', NULL, 'Phường', '40');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01279', 'Phường Ngọc Xuân', NULL, 'Phường', '40');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01282', 'Phường Đề Thám', NULL, 'Phường', '40');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01285', 'Phường Hoà Chung', NULL, 'Phường', '40');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01288', 'Phường Duyệt Trung', NULL, 'Phường', '40');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01693', 'Xã Vĩnh Quang', NULL, 'Xã', '40');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01705', 'Xã Hưng Đạo', NULL, 'Xã', '40');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01720', 'Xã Chu Trinh', NULL, 'Xã', '40');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01290', 'Thị trấn Pác Miầu', NULL, 'Thị trấn', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01291', 'Xã Đức Hạnh', NULL, 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01294', 'Xã Lý Bôn', NULL, 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01296', 'Xã Nam Cao', 'Nam Cao commune', 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01297', 'Xã Nam Quang', NULL, 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01300', 'Xã Vĩnh Quang', NULL, 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01303', 'Xã Quảng Lâm', NULL, 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01304', 'Xã Thạch Lâm', 'Thach Lam commune', 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01309', 'Xã Vĩnh Phong', NULL, 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01312', 'Xã Mông Ân', NULL, 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01315', 'Xã Thái Học', NULL, 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01316', 'Xã Thái Sơn', 'Thai Son commune', 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01318', 'Xã Yên Thổ', NULL, 'Xã', '42');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01321', 'Thị trấn Bảo Lạc', NULL, 'Thị trấn', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01324', 'Xã Cốc Pàng', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01327', 'Xã Thượng Hà', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01330', 'Xã Cô Ba', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01333', 'Xã Bảo Toàn', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01336', 'Xã Khánh Xuân', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01339', 'Xã Xuân Trường', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01342', 'Xã Hồng Trị', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01343', 'Xã Kim Cúc', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01345', 'Xã Phan Thanh', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01348', 'Xã Hồng An', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01351', 'Xã Hưng Đạo', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01352', 'Xã Hưng Thịnh', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01354', 'Xã Huy Giáp', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01357', 'Xã Đình Phùng', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01359', 'Xã Sơn Lập', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01360', 'Xã Sơn Lộ', NULL, 'Xã', '43');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01363', 'Thị trấn Thông Nông', NULL, 'Thị trấn', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01366', 'Xã Cần Yên', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01367', 'Xã Cần Nông', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01372', 'Xã Lương Thông', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01375', 'Xã Đa Thông', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01378', 'Xã Ngọc Động', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01381', 'Xã Yên Sơn', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01384', 'Xã Lương Can', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01387', 'Xã Thanh Long', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01392', 'Thị trấn Xuân Hòa', NULL, 'Thị trấn', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01393', 'Xã Lũng Nặm', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01399', 'Xã Trường Hà', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01402', 'Xã Cải Viên', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01411', 'Xã Nội Thôn', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01414', 'Xã Tổng Cọt', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01417', 'Xã Sóc Hà', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01420', 'Xã Thượng Thôn', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01429', 'Xã Hồng Sỹ', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01432', 'Xã Quý Quân', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01435', 'Xã Mã Ba', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01438', 'Xã Ngọc Đào', NULL, 'Xã', '45');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01447', 'Thị trấn Trà Lĩnh', NULL, 'Thị trấn', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01453', 'Xã Tri Phương', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01456', 'Xã Quang Hán', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01462', 'Xã Xuân Nội', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01465', 'Xã Quang Trung', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01468', 'Xã Quang Vinh', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01471', 'Xã Cao Chương', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01477', 'Thị trấn Trùng Khánh', NULL, 'Thị trấn', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01480', 'Xã Ngọc Khê', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01481', 'Xã Ngọc Côn', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01483', 'Xã Phong Nậm', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01489', 'Xã Đình Phong', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01495', 'Xã Đàm Thuỷ', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01498', 'Xã Khâm Thành', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01501', 'Xã Chí Viễn', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01504', 'Xã Lăng Hiếu', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01507', 'Xã Phong Châu', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01516', 'Xã Trung Phúc', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01519', 'Xã Cao Thăng', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01522', 'Xã Đức Hồng', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01525', 'Xã Đoài Dương', NULL, 'Xã', '47');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01534', 'Xã Minh Long', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01537', 'Xã Lý Quốc', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01540', 'Xã Thắng Lợi', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01543', 'Xã Đồng Loan', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01546', 'Xã Đức Quang', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01549', 'Xã Kim Loan', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01552', 'Xã Quang Long', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01555', 'Xã An Lạc', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01558', 'Thị trấn Thanh Nhật', NULL, 'Thị trấn', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01561', 'Xã Vinh Quý', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01564', 'Xã Thống Nhất', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01567', 'Xã Cô Ngân', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01573', 'Xã Thị Hoa', NULL, 'Xã', '48');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01474', 'Xã Quốc Toản', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01576', 'Thị trấn Quảng Uyên', NULL, 'Thị trấn', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01579', 'Xã Phi Hải', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01582', 'Xã Quảng Hưng', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01594', 'Xã Độc Lập', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01597', 'Xã Cai Bộ', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01603', 'Xã Phúc Sen', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01606', 'Xã Chí Thảo', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01609', 'Xã Tự Do', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01615', 'Xã Hồng Quang', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01618', 'Xã Ngọc Động', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01624', 'Xã Hạnh Phúc', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01627', 'Thị trấn Tà Lùng', NULL, 'Thị trấn', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01630', 'Xã Bế Văn Đàn', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01636', 'Xã Cách Linh', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01639', 'Xã Đại Sơn', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01645', 'Xã Tiên Thành', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01648', 'Thị trấn Hoà Thuận', NULL, 'Thị trấn', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01651', 'Xã Mỹ Hưng', NULL, 'Xã', '49');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01654', 'Thị trấn Nước Hai', NULL, 'Thị trấn', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01657', 'Xã Dân Chủ', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01660', 'Xã Nam Tuấn', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01666', 'Xã Đại Tiến', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01669', 'Xã Đức Long', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01672', 'Xã Ngũ Lão', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01675', 'Xã Trương Lương', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01687', 'Xã Hồng Việt', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01696', 'Xã Hoàng Tung', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01699', 'Xã Nguyễn Huệ', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01702', 'Xã Quang Trung', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01708', 'Xã Bạch Đằng', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01711', 'Xã Bình Dương', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01714', 'Xã Lê Chung', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01723', 'Xã Hồng Nam', NULL, 'Xã', '51');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01726', 'Thị trấn Nguyên Bình', NULL, 'Thị trấn', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01729', 'Thị trấn Tĩnh Túc', NULL, 'Thị trấn', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01732', 'Xã Yên Lạc', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01735', 'Xã Triệu Nguyên', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01738', 'Xã Ca Thành', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01744', 'Xã Vũ Nông', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01747', 'Xã Minh Tâm', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01750', 'Xã Thể Dục', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01756', 'Xã Mai Long', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01762', 'Xã Vũ Minh', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01765', 'Xã Hoa Thám', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01768', 'Xã Phan Thanh', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01771', 'Xã Quang Thành', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01774', 'Xã Tam Kim', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01777', 'Xã Thành Công', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01780', 'Xã Thịnh Vượng', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01783', 'Xã Hưng Đạo', NULL, 'Xã', '52');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01786', 'Thị trấn Đông Khê', NULL, 'Thị trấn', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01789', 'Xã Canh Tân', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01792', 'Xã Kim Đồng', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01795', 'Xã Minh Khai', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01801', 'Xã Đức Thông', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01804', 'Xã Thái Cường', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01807', 'Xã Vân Trình', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01810', 'Xã Thụy Hùng', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01813', 'Xã Quang Trọng', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01816', 'Xã Trọng Con', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01819', 'Xã Lê Lai', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01822', 'Xã Đức Long', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01828', 'Xã Lê Lợi', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01831', 'Xã Đức Xuân', NULL, 'Xã', '53');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01834', 'Phường Nguyễn Thị Minh Khai', NULL, 'Phường', '58');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01837', 'Phường Sông Cầu', NULL, 'Phường', '58');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01840', 'Phường Đức Xuân', NULL, 'Phường', '58');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01843', 'Phường Phùng Chí Kiên', NULL, 'Phường', '58');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01846', 'Phường Huyền Tụng', NULL, 'Phường', '58');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01849', 'Xã Dương Quang', NULL, 'Xã', '58');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01852', 'Xã Nông Thượng', NULL, 'Xã', '58');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01855', 'Phường Xuất Hóa', NULL, 'Phường', '58');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01858', 'Xã Bằng Thành', NULL, 'Xã', '60');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01861', 'Xã Nhạn Môn', NULL, 'Xã', '60');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01864', 'Xã Bộc Bố', NULL, 'Xã', '60');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('01867', 'Xã Công Bằng', NULL, 'Xã', '60');