INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04795', 'Phường Thịnh Lang', NULL, 'Phường', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04798', 'Phường Hữu Nghị', NULL, 'Phường', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04801', 'Phường Tân Thịnh', NULL, 'Phường', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04804', 'Phường Đồng Tiến', NULL, 'Phường', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04807', 'Phường Phương Lâm', NULL, 'Phường', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04813', 'Xã Yên Mông', NULL, 'Xã', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04816', 'Phường Quỳnh Lâm', NULL, 'Phường', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04819', 'Phường Dân Chủ', NULL, 'Phường', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04825', 'Xã Hòa Bình', NULL, 'Xã', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04828', 'Phường Thống Nhất', NULL, 'Phường', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04894', 'Phường Kỳ Sơn', NULL, 'Phường', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04897', 'Xã Thịnh Minh', NULL, 'Xã', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04903', 'Xã Hợp Thành', NULL, 'Xã', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04906', 'Xã Quang Tiến', NULL, 'Xã', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04912', 'Xã Mông Hóa', NULL, 'Xã', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04918', 'Phường Trung Minh', NULL, 'Phường', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04921', 'Xã Độc Lập', NULL, 'Xã', '148');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04831', 'Thị trấn Đà Bắc', NULL, 'Thị trấn', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04834', 'Xã Nánh Nghê', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04840', 'Xã Giáp Đắt', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04846', 'Xã Mường Chiềng', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04849', 'Xã Tân Pheo', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04852', 'Xã Đồng Chum', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04855', 'Xã Tân Minh', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04858', 'Xã Đoàn Kết', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04861', 'Xã Đồng Ruộng', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04867', 'Xã Tú Lý', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04870', 'Xã Trung Thành', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04873', 'Xã Yên Hòa', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04876', 'Xã Cao Sơn', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04879', 'Xã Toàn Sơn', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04885', 'Xã Hiền Lương', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04888', 'Xã Tiền Phong', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04891', 'Xã Vầy Nưa', NULL, 'Xã', '150');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04924', 'Thị trấn Lương Sơn', NULL, 'Thị trấn', '152');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04942', 'Xã Lâm Sơn', NULL, 'Xã', '152');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04945', 'Xã Hòa Sơn', NULL, 'Xã', '152');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04951', 'Xã Tân Vinh', NULL, 'Xã', '152');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04954', 'Xã Nhuận Trạch', NULL, 'Xã', '152');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04957', 'Xã Cao Sơn', NULL, 'Xã', '152');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04960', 'Xã Cư Yên', NULL, 'Xã', '152');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04969', 'Xã Liên Sơn', NULL, 'Xã', '152');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05008', 'Xã Cao Dương', NULL, 'Xã', '152');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05041', 'Xã Thanh Sơn', NULL, 'Xã', '152');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05047', 'Xã Thanh Cao', NULL, 'Xã', '152');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04978', 'Thị trấn Bo', NULL, 'Thị trấn', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04984', 'Xã Đú Sáng', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04987', 'Xã Hùng Sơn', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04990', 'Xã Bình Sơn', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04999', 'Xã Tú Sơn', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05005', 'Xã Vĩnh Tiến', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05014', 'Xã Đông Bắc', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05017', 'Xã Xuân Thủy', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05026', 'Xã Vĩnh Đồng', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05035', 'Xã Kim Lập', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05038', 'Xã Hợp Tiến', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05065', 'Xã Kim Bôi', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05068', 'Xã Nam Thượng', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05077', 'Xã Cuối Hạ', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05080', 'Xã Sào Báy', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05083', 'Xã Mi Hòa', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05086', 'Xã Nuông Dăm', NULL, 'Xã', '153');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05089', 'Thị trấn Cao Phong', NULL, 'Thị trấn', '154');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05092', 'Xã Bình Thanh', NULL, 'Xã', '154');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05095', 'Xã Thung Nai', NULL, 'Xã', '154');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05098', 'Xã Bắc Phong', NULL, 'Xã', '154');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05101', 'Xã Thu Phong', NULL, 'Xã', '154');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05104', 'Xã Hợp Phong', NULL, 'Xã', '154');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05110', 'Xã Tây Phong', NULL, 'Xã', '154');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05116', 'Xã Dũng Phong', NULL, 'Xã', '154');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05119', 'Xã Nam Phong', NULL, 'Xã', '154');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05125', 'Xã Thạch Yên', NULL, 'Xã', '154');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05128', 'Thị trấn Mãn Đức', NULL, 'Thị trấn', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05134', 'Xã Suối Hoa', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05137', 'Xã Phú Vinh', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05140', 'Xã Phú Cường', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05143', 'Xã Mỹ Hòa', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05152', 'Xã Quyết Chiến', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05158', 'Xã Phong Phú', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05164', 'Xã Tử Nê', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05167', 'Xã Thanh Hối', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05170', 'Xã Ngọc Mỹ', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05173', 'Xã Đông Lai',
        NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05176', 'Xã Vân Sơn', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05182', 'Xã Nhân Mỹ', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05191', 'Xã Lỗ Sơn', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05194', 'Xã Ngổ Luông', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05197', 'Xã Gia Mô', NULL, 'Xã', '155');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04882', 'Xã Tân Thành', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05200', 'Thị trấn Mai Châu', NULL, 'Thị trấn', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05206', 'Xã Sơn Thủy', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05209', 'Xã Pà Cò', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05212', 'Xã Hang Kia', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05221', 'Xã Đồng Tân', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05224', 'Xã Cun Pheo', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05227', 'Xã Bao La', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05233', 'Xã Tòng Đậu', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05242', 'Xã Nà Phòn', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05245', 'Xã Săm Khóe', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05248', 'Xã Chiềng Châu', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05251', 'Xã Mai Hạ', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05254', 'Xã Thành Sơn', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05257', 'Xã Mai Hịch', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05263', 'Xã Vạn Mai', NULL, 'Xã', '156');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05266', 'Thị trấn Vụ Bản', NULL, 'Thị trấn', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05269', 'Xã Quý Hòa', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05272', 'Xã Miền Đồi', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05275', 'Xã Mỹ Thành', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05278', 'Xã Tuân Đạo', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05281', 'Xã Văn Nghĩa', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05284', 'Xã Văn Sơn', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05287', 'Xã Tân Lập', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05290', 'Xã Nhân Nghĩa', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05293', 'Xã Thượng Cốc', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05299', 'Xã Quyết Thắng', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05302', 'Xã Xuất Hóa', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05305', 'Xã Yên Phú', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05308', 'Xã Bình Hẻm', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05320', 'Xã Định Cư', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05323', 'Xã Chí Đạo', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05329', 'Xã Ngọc Sơn', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05332', 'Xã Hương Nhượng', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05335', 'Xã Vũ Bình', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05338', 'Xã Tự Do', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05341', 'Xã Yên Nghiệp', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05344', 'Xã Tân Mỹ', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05347', 'Xã Ân Nghĩa', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05350', 'Xã Ngọc Lâu', NULL, 'Xã', '157');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05353', 'Thị trấn Hàng Trạm', NULL, 'Thị trấn', '158');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05356', 'Xã Lạc Sỹ', NULL, 'Xã', '158');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05362', 'Xã Lạc Lương', NULL, 'Xã', '158');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05365', 'Xã Bảo Hiệu', NULL, 'Xã', '158');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05368', 'Xã Đa Phúc', NULL, 'Xã', '158');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05371', 'Xã Hữu Lợi', NULL, 'Xã', '158');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05374', 'Xã Lạc Thịnh', NULL, 'Xã', '158');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05380', 'Xã Đoàn Kết', NULL, 'Xã', '158');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05383', 'Xã Phú Lai', NULL, 'Xã', '158');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05386', 'Xã Yên Trị', NULL, 'Xã', '158');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05389', 'Xã Ngọc Lương', NULL, 'Xã', '158');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('04981', 'Thị trấn Ba Hàng Đồi', NULL, 'Thị trấn', '159');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05392', 'Thị trấn Chi Nê', NULL, 'Thị trấn', '159');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05395', 'Xã Phú Nghĩa', NULL, 'Xã', '159');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05398', 'Xã Phú Thành', NULL, 'Xã', '159');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05404', 'Xã Hưng Thi', NULL, 'Xã', '159');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05413', 'Xã Khoan Dụ', NULL, 'Xã', '159');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05419', 'Xã Đồng Tâm', NULL, 'Xã', '159');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05422', 'Xã Yên Bồng', NULL, 'Xã', '159');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05425', 'Xã Thống Nhất', NULL, 'Xã', '159');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05428', 'Xã An Bình', NULL, 'Xã', '159');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05431', 'Phường Quán Triều', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05434', 'Phường Quang Vinh', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05437', 'Phường Túc Duyên', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05440', 'Phường Hoàng Văn Thụ', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05443', 'Phường Trưng Vương', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05446', 'Phường Quang Trung', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05449', 'Phường Phan Đình Phùng', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05452', 'Phường Tân Thịnh', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05455', 'Phường Thịnh Đán', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05458', 'Phường Đồng Quang', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05461', 'Phường Gia Sàng', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05464', 'Phường Tân Lập', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05467', 'Phường Cam Giá', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05470', 'Phường Phú Xá', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05473', 'Phường Hương Sơn', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05476', 'Phường Trung Thành', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05479', 'Phường Tân Thành', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05482', 'Phường Tân Long', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05485', 'Xã Phúc Hà', NULL, 'Xã', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05488', 'Xã Phúc Xuân', NULL, 'Xã', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05491', 'Xã Quyết Thắng', NULL, 'Xã', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05494', 'Xã Phúc Trìu', NULL, 'Xã', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05497', 'Xã Thịnh Đức', NULL, 'Xã', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05500', 'Phường Tích Lương', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05503', 'Xã Tân Cương', NULL, 'Xã', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05653', 'Xã Sơn Cẩm', NULL, 'Xã', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05659', 'Phường Chùa Hang', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05695', 'Xã Cao Ngạn', NULL, 'Xã', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05701', 'Xã Linh Sơn', NULL, 'Xã', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05710', 'Phường Đồng Bẩm', NULL, 'Phường', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05713', 'Xã Huống Thượng', NULL, 'Xã', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05914', 'Xã Đồng Liên', NULL, 'Xã', '164');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05506', 'Phường Lương Sơn', NULL, 'Phường', '165');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05509', 'Phường Châu Sơn', NULL, 'Phường', '165');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05512', 'Phường Mỏ Chè', NULL, 'Phường', '165');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05515', 'Phường Cải Đan', NULL, 'Phường', '165');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05518', 'Phường Thắng Lợi', NULL, 'Phường', '165');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05521', 'Phường Phố Cò', NULL, 'Phường', '165');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05527', 'Xã Tân Quang', NULL, 'Xã', '165');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05528', 'Phường Bách Quang', NULL, 'Phường', '165');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05530', 'Xã Bình Sơn', NULL, 'Xã', '165');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05533', 'Xã Bá Xuyên', NULL, 'Xã', '165');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05539', 'Xã Linh Thông', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05542', 'Xã Lam Vỹ', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05545', 'Xã Quy Kỳ', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05548', 'Xã Tân Thịnh', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05551', 'Xã Kim Phượng', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05554', 'Xã Bảo Linh', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05560', 'Xã Phúc Chu', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05563', 'Xã Tân Dương', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05566', 'Xã Phượng Tiến', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05569', 'Thị trấn Chợ Chu', NULL, 'Thị trấn', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05572', 'Xã Đồng Thịnh', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05575', 'Xã Định Biên', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05578', 'Xã Thanh Định', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05581', 'Xã Trung Hội', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05584', 'Xã Trung Lương', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05587', 'Xã Bình Yên', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05590', 'Xã Điềm Mặc', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05593', 'Xã Phú Tiến', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05596', 'Xã Bộc Nhiêu', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05599', 'Xã Sơn Phú', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05602', 'Xã Phú Đình', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05605', 'Xã Bình Thành', NULL, 'Xã', '167');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05611', 'Thị trấn Đu', NULL, 'Thị trấn', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05614', 'Xã Yên Ninh', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05617', 'Xã Yên Trạch', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05620', 'Xã Yên Đổ', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05623', 'Xã Yên Lạc', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05626', 'Xã Ôn Lương', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05629', 'Xã Động Đạt', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05632', 'Xã Phủ Lý', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05635', 'Xã Phú Đô', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05638', 'Xã Hợp Thành', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05641', 'Xã Tức Tranh', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05644', 'Thị trấn Giang Tiên', NULL, 'Thị trấn', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05647', 'Xã Vô Tranh', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05650', 'Xã Cổ Lũng', NULL, 'Xã', '168');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05656', 'Thị trấn Sông Cầu', NULL, 'Thị trấn', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05662', 'Thị trấn Trại Cau', NULL, 'Thị trấn', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05665', 'Xã Văn Lăng', NULL, 'Xã', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05668', 'Xã Tân Long', NULL, 'Xã', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05671', 'Xã Hòa Bình', NULL, 'Xã', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05674', 'Xã Quang Sơn', NULL, 'Xã', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05677', 'Xã Minh Lập', NULL, 'Xã', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05680', 'Xã Văn Hán', NULL, 'Xã', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05683', 'Xã Hóa Trung', NULL, 'Xã', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05686', 'Xã Khe Mo', NULL, 'Xã', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05689', 'Xã Cây Thị', NULL, 'Xã', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05692', 'Thị trấn Hóa Thượng', NULL, 'Thị trấn', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05698', 'Xã Hợp Tiến', NULL, 'Xã', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05707', 'Xã Nam Hòa', NULL, 'Xã', '169');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05716', 'Thị trấn Đình Cả', NULL, 'Thị trấn', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05719', 'Xã Sảng Mộc', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05722', 'Xã Nghinh Tường', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05725', 'Xã Thần Xa', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05728', 'Xã Vũ Chấn', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05731', 'Xã Thượng Nung', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05734', 'Xã Phú Thượng', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05737', 'Xã Cúc Đường', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05740', 'Xã La Hiên', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05743', 'Xã Lâu Thượng', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05746', 'Xã Tràng Xá', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05749', 'Xã Phương Giao', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05752', 'Xã Liên Minh', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05755', 'Xã Dân Tiến', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05758', 'Xã Bình Long', NULL, 'Xã', '170');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05761', 'Thị trấn Hùng Sơn', NULL, 'Thị trấn', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05767', 'Xã Phúc Lương', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05770', 'Xã Minh Tiến', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05773', 'Xã Yên Lãng', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05776', 'Xã Đức Lương', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05779', 'Xã Phú Cường', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05785', 'Xã Phú Lạc', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05788', 'Xã Tân Linh', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05791', 'Xã Phú Thịnh', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05794', 'Xã Phục Linh', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05797', 'Xã Phú Xuyên', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05800', 'Xã Bản Ngoại', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05803', 'Xã Tiên Hội', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05809', 'Xã Cù Vân', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05812', 'Xã Hà Thượng', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05815', 'Xã La Bằng', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05818', 'Xã Hoàng Nông', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05821', 'Xã Khôi Kỳ', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05824', 'Xã An Khánh', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05827', 'Xã Tân Thái', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05830', 'Xã Bình Thuận', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05833', 'Xã Lục Ba', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05836', 'Xã Mỹ Yên', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05842', 'Xã Văn Yên', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05845', 'Xã Vạn Phú', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05848', 'Xã Cát Nê', NULL, 'Xã', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05851', 'Thị trấn Quân Chu', NULL, 'Thị trấn', '171');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05854', 'Phường Bãi Bông', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05857', 'Phường Bắc Sơn', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05860', 'Phường Ba Hàng', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05863', 'Xã Phúc Tân', NULL, 'Xã', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05866', 'Xã Phúc Thuận', NULL, 'Xã', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05869', 'Phường Hồng Tiến', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05872', 'Xã Minh Đức', NULL, 'Xã', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05875', 'Phường Đắc Sơn', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05878', 'Phường Đồng Tiến', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05881', 'Xã Thành Công', NULL, 'Xã', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05884', 'Phường Tiên Phong', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05887', 'Xã Vạn Phái', NULL, 'Xã', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05890', 'Phường Nam Tiến', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05893', 'Phường Tân Hương', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05896', 'Phường Đông Cao', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05899', 'Phường Trung Thành', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05902', 'Phường Tân Phú', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05905', 'Phường Thuận Thành', NULL, 'Phường', '172');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05908', 'Thị trấn Hương Sơn', NULL, 'Thị trấn', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05911', 'Xã Bàn Đạt', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05917', 'Xã Tân Khánh', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05920', 'Xã Tân Kim', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05923', 'Xã Tân Thành', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05926', 'Xã Đào Xá', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05929', 'Xã Bảo Lý', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05932', 'Xã Thượng Đình', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05935', 'Xã Tân Hòa', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05938', 'Xã Nhã Lộng', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05941', 'Xã Điềm Thụy', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05944', 'Xã Xuân Phương', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05947', 'Xã Tân Đức', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05950', 'Xã Úc Kỳ', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05953', 'Xã Lương Phú', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05956', 'Xã Nga My', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05959', 'Xã Kha Sơn', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05962', 'Xã Thanh Ninh', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05965', 'Xã Dương Thành', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05968', 'Xã Hà Châu', NULL, 'Xã', '173');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05971', 'Phường Hoàng Văn Thụ', NULL, 'Phường', '178');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05974', 'Phường Tam Thanh', NULL, 'Phường', '178');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05977', 'Phường Vĩnh Trại', NULL, 'Phường', '178');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05980', 'Phường Đông Kinh', NULL, 'Phường', '178');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05983', 'Phường Chi Lăng', NULL, 'Phường', '178');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05986', 'Xã Hoàng Đồng', NULL, 'Xã', '178');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05989', 'Xã Quảng Lạc', NULL, 'Xã', '178');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05992', 'Xã Mai Pha', NULL, 'Xã', '178');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('05998', 'Xã Khánh Long', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06001', 'Xã Đoàn Kết', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06004', 'Xã Quốc Khánh', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06010', 'Xã Cao Minh', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06013', 'Xã Chí Minh', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06016', 'Xã Tri Phương', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06019', 'Xã Tân Tiến', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06022', 'Xã Tân Yên', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06025', 'Xã Đội Cấn', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06028', 'Xã Tân Minh', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06031', 'Xã Kim Đồng', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06034', 'Xã Chi Lăng', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06037', 'Xã Trung Thành', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06040', 'Thị trấn Thất Khê', NULL, 'Thị trấn', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06043', 'Xã Đào Viên', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06046', 'Xã Đề Thám', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06049', 'Xã Kháng Chiến', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06055', 'Xã Hùng Sơn', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06058', 'Xã Quốc Việt', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06061', 'Xã Hùng Việt', NULL, 'Xã', '180');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06067', 'Xã Hưng Đạo', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06070', 'Xã Vĩnh Yên', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06073', 'Xã Hoa Thám', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06076', 'Xã Quý Hòa', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06079', 'Xã Hồng Phong', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06082', 'Xã Yên Lỗ', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06085', 'Xã Thiện Hòa', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06088', 'Xã Quang Trung', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06091', 'Xã Thiện Thuật', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06094', 'Xã Minh Khai', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06097', 'Xã Thiện Long', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06100', 'Xã Hoàng Văn Thụ', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06103', 'Xã Hòa Bình', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06106', 'Xã Mông Ân', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06109', 'Xã Tân Hòa', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06112', 'Thị trấn Bình Gia', NULL, 'Thị trấn', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06115', 'Xã Hồng Thái', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06118', 'Xã Bình La', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06121', 'Xã Tân Văn', NULL, 'Xã', '181');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06124', 'Thị trấn Na Sầm', NULL, 'Thị trấn', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06127', 'Xã Trùng Khánh', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06133', 'Xã Bắc La', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06136', 'Xã Thụy Hùng', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06139', 'Xã Bắc Hùng', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06142', 'Xã Tân Tác', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06148', 'Xã Thanh Long', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06151', 'Xã Hội Hoan', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06154', 'Xã Bắc Việt', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06157', 'Xã Hoàng Việt', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06160', 'Xã Gia Miễn', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06163', 'Xã Thành Hòa', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06166', 'Xã Tân Thanh', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06172', 'Xã Tân Mỹ', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06175', 'Xã Hồng Thái', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06178', 'Xã  Hoàng Văn Thụ', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06181', 'Xã Nhạc Kỳ', NULL, 'Xã', '182');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06184', 'Thị trấn Đồng Đăng', NULL, 'Thị trấn', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06187', 'Thị trấn Cao Lộc', NULL, 'Thị trấn', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06190', 'Xã Bảo Lâm', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06193', 'Xã Thanh Lòa', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06196', 'Xã Cao Lâu', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06199', 'Xã Thạch Đạn', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06202', 'Xã Xuất Lễ', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06205', 'Xã Hồng Phong', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06208', 'Xã Thụy Hùng', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06211', 'Xã Lộc Yên', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06214', 'Xã Phú Xá', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06217', 'Xã Bình Trung', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06220', 'Xã Hải Yến', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06223', 'Xã Hòa Cư', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06226', 'Xã Hợp Thành', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06232', 'Xã Công Sơn', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06235', 'Xã Gia Cát', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06238', 'Xã Mẫu Sơn', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06241', 'Xã Xuân Long', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06244', 'Xã Tân Liên', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06247', 'Xã Yên Trạch', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06250', 'Xã Tân Thành', NULL, 'Xã', '183');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06253', 'Thị trấn Văn Quan', NULL, 'Thị trấn', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06256', 'Xã Trấn Ninh', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06268', 'Xã Liên Hội', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06274', 'Xã Hòa Bình', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06277', 'Xã Tú Xuyên', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06280', 'Xã Điềm He', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06283', 'Xã An Sơn', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06286', 'Xã Khánh Khê', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06292', 'Xã Lương Năng', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06298', 'Xã Bình Phúc', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06307', 'Xã Tân Đoàn', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06313', 'Xã Tri Lễ', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06316', 'Xã Tràng Phái', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06319', 'Xã Yên Phúc', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06322', 'Xã Hữu Lễ', NULL, 'Xã', '184');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06325', 'Thị trấn Bắc Sơn', NULL, 'Thị trấn', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06328', 'Xã Long Đống', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06331', 'Xã Vạn Thủy', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06337', 'Xã Đồng ý', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06340', 'Xã Tân Tri', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06343', 'Xã Bắc Quỳnh', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06349', 'Xã Hưng Vũ', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06352', 'Xã Tân Lập', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06355', 'Xã Vũ Sơn', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06358', 'Xã Chiêu Vũ', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06361', 'Xã Tân Hương', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06364', 'Xã Chiến Thắng', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06367', 'Xã Vũ Lăng', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06370', 'Xã Trấn Yên', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06373', 'Xã Vũ Lễ', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06376', 'Xã Nhất Hòa', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06379', 'Xã Tân Thành', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06382', 'Xã Nhất Tiến', NULL, 'Xã', '185');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06385', 'Thị trấn Hữu Lũng', NULL, 'Thị trấn', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06388', 'Xã Hữu Liên', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06391', 'Xã Yên Bình', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06394', 'Xã Quyết Thắng', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06397', 'Xã Hòa Bình', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06400', 'Xã Yên Thịnh', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06403', 'Xã Yên Sơn', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06406', 'Xã Thiện Tân', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06412', 'Xã Yên Vượng', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06415', 'Xã Minh Tiến', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06418', 'Xã Nhật Tiến', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06421', 'Xã Thanh Sơn', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06424', 'Xã Đồng Tân', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06427', 'Xã Cai Kinh', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06430', 'Xã Hòa Lạc', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06433', 'Xã Vân Nham', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06436', 'Xã Đồng Tiến', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06442', 'Xã Tân Thành', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06445', 'Xã Hòa Sơn', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06448', 'Xã Minh Sơn', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06451', 'Xã Hồ Sơn', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06457', 'Xã Minh Hòa', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06460', 'Xã Hòa Thắng', NULL, 'Xã', '186');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06463', 'Thị trấn Đồng Mỏ', NULL, 'Thị trấn', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06466', 'Thị trấn Chi Lăng', NULL, 'Thị trấn', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06469', 'Xã Vân An', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06472', 'Xã Vân Thủy', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06475', 'Xã Gia Lộc', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06478', 'Xã Bắc Thủy', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06481', 'Xã Chiến Thắng', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06484', 'Xã Mai Sao', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06487', 'Xã Bằng Hữu', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06490', 'Xã Thượng Cường', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06493', 'Xã Bằng Mạc', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06496', 'Xã Nhân Lý', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06499', 'Xã Lâm Sơn', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06502', 'Xã Liên Sơn', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06505', 'Xã Vạn Linh', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06508', 'Xã Hòa Bình', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06514', 'Xã Hữu Kiên', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06517', 'Xã Quan Sơn', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06520', 'Xã Y Tịch', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06523', 'Xã Chi Lăng', NULL, 'Xã', '187');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06526', 'Thị trấn Na Dương', NULL, 'Thị trấn', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06529', 'Thị trấn Lộc Bình', NULL, 'Thị trấn', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06532', 'Xã Mẫu Sơn', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06541', 'Xã Yên Khoái', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06544', 'Xã Khánh Xuân', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06547', 'Xã Tú Mịch', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06550', 'Xã Hữu Khánh', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06553', 'Xã Đồng Bục', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06559', 'Xã Tam Gia', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06562', 'Xã Tú Đoạn', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06565', 'Xã Khuất Xá', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06577', 'Xã Thống Nhất', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06589', 'Xã Sàn Viên', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06592', 'Xã Đông Quan', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06595', 'Xã Minh Hiệp', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06598', 'Xã Hữu Lân', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06601', 'Xã Lợi Bác', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06604', 'Xã Nam Quan', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06607', 'Xã Xuân Dương', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06610', 'Xã Ái Quốc', NULL, 'Xã', '188');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06613', 'Thị trấn Đình Lập', NULL, 'Thị trấn', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06616', 'Thị trấn NT Thái Bình', NULL, 'Thị trấn', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06619', 'Xã Bắc Xa', NULL, 'Xã', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06622', 'Xã Bính Xá', NULL, 'Xã', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06625', 'Xã Kiên Mộc', NULL, 'Xã', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06628', 'Xã Đình Lập', NULL, 'Xã', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06631', 'Xã Thái Bình', NULL, 'Xã', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06634', 'Xã Cường Lợi', NULL, 'Xã', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06637', 'Xã Châu Sơn', NULL, 'Xã', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06640', 'Xã Lâm Ca', NULL, 'Xã', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06643', 'Xã Đồng Thắng', NULL, 'Xã', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06646', 'Xã Bắc Lãng', NULL, 'Xã', '189');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06649', 'Phường Hà Khánh', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06652', 'Phường Hà Phong', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06655', 'Phường Hà Khẩu', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06658', 'Phường Cao Xanh', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06661', 'Phường Giếng Đáy', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06664', 'Phường Hà Tu', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06667', 'Phường Hà Trung', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06670', 'Phường Hà Lầm', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06673', 'Phường Bãi Cháy', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06676', 'Phường Cao Thắng', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06679', 'Phường Hùng Thắng', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06685', 'Phường Trần Hưng Đạo', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06688', 'Phường Hồng Hải', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06691', 'Phường Hồng Gai', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06694', 'Phường Bạch Đằng', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06697', 'Phường Hồng Hà', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06700', 'Phường Tuần Châu', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06703', 'Phường Việt Hưng', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06706', 'Phường Đại Yên', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07030', 'Phường Hoành Bồ', NULL, 'Phường', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07033', 'Xã Kỳ Thượng', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07036', 'Xã Đồng Sơn', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07039', 'Xã Tân Dân', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07042', 'Xã Đồng Lâm', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07045', 'Xã Hòa Bình', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07048', 'Xã Vũ Oai', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07051', 'Xã Dân Chủ', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07054', 'Xã Quảng La', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07057', 'Xã Bằng Cả', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07060', 'Xã Thống Nhất', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07063', 'Xã Sơn Dương', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07066', 'Xã Lê Lợi', NULL, 'Xã', '193');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06709', 'Phường Ka Long', NULL, 'Phường', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06712', 'Phường Trần Phú', NULL, 'Phường', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06715', 'Phường Ninh Dương', NULL, 'Phường', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06721', 'Phường Trà Cổ', NULL, 'Phường', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06724', 'Xã Hải Sơn', NULL, 'Xã', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06727', 'Xã Bắc Sơn', NULL, 'Xã', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06730', 'Xã Hải Đông', NULL, 'Xã', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06733', 'Xã Hải Tiến', NULL, 'Xã', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06736', 'Phường Hải Yên', NULL, 'Phường', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06739', 'Xã Quảng Nghĩa', NULL, 'Xã', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06742', 'Phường Hải Hoà', NULL, 'Phường', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06745', 'Xã Hải Xuân', NULL, 'Xã', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06748', 'Xã Vạn Ninh', NULL, 'Xã', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06751', 'Phường Bình Ngọc', NULL, 'Phường', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06754', 'Xã Vĩnh Trung', NULL, 'Xã', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06757', 'Xã Vĩnh Thực', NULL, 'Xã', '194');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06760', 'Phường Mông Dương', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06763', 'Phường Cửa Ông', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06766', 'Phường Cẩm Sơn', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06769', 'Phường Cẩm Đông', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06772', 'Phường Cẩm Phú', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06775', 'Phường Cẩm Tây', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06778', 'Phường Quang Hanh', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06781', 'Phường Cẩm Thịnh', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06784', 'Phường Cẩm Thủy', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06787', 'Phường Cẩm Thạch', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06790', 'Phường Cẩm Thành', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06793', 'Phường Cẩm Trung', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06796', 'Phường Cẩm Bình', NULL, 'Phường', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06799', 'Xã Hải Hòa', NULL, 'Xã', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06805', 'Xã Dương Huy', NULL, 'Xã', '195');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06808', 'Phường Vàng Danh', NULL, 'Phường', '196');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06811', 'Phường Thanh Sơn', NULL, 'Phường', '196');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06814', 'Phường Bắc Sơn', NULL, 'Phường', '196');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06817', 'Phường Quang Trung', NULL, 'Phường', '196');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06820', 'Phường Trưng Vương', NULL, 'Phường', '196');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06823', 'Phường Nam Khê', NULL, 'Phường', '196');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06826', 'Phường Yên Thanh', NULL, 'Phường', '196');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06829', 'Xã Thượng Yên Công', NULL, 'Xã', '196');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06832', 'Phường Phương Đông', NULL, 'Phường', '196');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06835', 'Phường Phương Nam', NULL, 'Phường', '196');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06838', 'Thị trấn Bình Liêu', NULL, 'Thị trấn', '198');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06841', 'Xã Hoành Mô', NULL, 'Xã', '198');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06844', 'Xã Đồng Tâm', NULL, 'Xã', '198');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06847', 'Xã Đồng Văn', NULL, 'Xã', '198');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06853', 'Xã Vô Ngại', NULL, 'Xã', '198');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06856', 'Xã Lục Hồn', NULL, 'Xã', '198');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06859', 'Xã Húc Động', NULL, 'Xã', '198');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06862', 'Thị trấn Tiên Yên', NULL, 'Thị trấn', '199');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06865', 'Xã Hà Lâu', NULL, 'Xã', '199');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06868', 'Xã Đại Dực', NULL, 'Xã', '199');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06871', 'Xã Phong Dụ', NULL, 'Xã', '199');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06874', 'Xã Điền Xá', NULL, 'Xã', '199');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06877', 'Xã Đông Ngũ', NULL, 'Xã', '199');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06880', 'Xã Yên Than', NULL, 'Xã', '199');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06883', 'Xã Đông Hải', NULL, 'Xã', '199');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06886', 'Xã Hải Lạng', NULL, 'Xã', '199');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06889', 'Xã Tiên Lãng', NULL, 'Xã', '199');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06892', 'Xã Đồng Rui', NULL, 'Xã', '199');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06895', 'Thị trấn Đầm Hà', NULL, 'Thị trấn', '200');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06898', 'Xã Quảng Lâm', NULL, 'Xã', '200');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06901', 'Xã Quảng An', NULL, 'Xã', '200');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06904', 'Xã Tân Bình', NULL, 'Xã', '200');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06910', 'Xã Dực Yên', NULL, 'Xã', '200');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06913', 'Xã Quảng Tân', NULL, 'Xã', '200');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06916', 'Xã Đầm Hà', NULL, 'Xã', '200');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06917', 'Xã Tân Lập', 'Tan Lap commune', 'Xã', '200');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06919', 'Xã Đại Bình', NULL, 'Xã', '200');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06922', 'Thị trấn Quảng Hà', NULL, 'Thị trấn', '201');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06925', 'Xã Quảng Đức', NULL, 'Xã', '201');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06928', 'Xã Quảng Sơn', NULL, 'Xã', '201');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06931', 'Xã Quảng Thành', NULL, 'Xã', '201');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06937', 'Xã Quảng Thịnh', NULL, 'Xã', '201');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06940', 'Xã Quảng Minh', NULL, 'Xã', '201');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06943', 'Xã Quảng Chính', NULL, 'Xã', '201');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06946', 'Xã Quảng Long', NULL, 'Xã', '201');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06949', 'Xã Đường Hoa', NULL, 'Xã', '201');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06952', 'Xã Quảng Phong', NULL, 'Xã', '201');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06967', 'Xã Cái Chiên', NULL, 'Xã', '201');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06970', 'Thị trấn Ba Chẽ', NULL, 'Thị trấn', '202');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06973', 'Xã Thanh Sơn', NULL, 'Xã', '202');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06976', 'Xã Thanh Lâm', NULL, 'Xã', '202');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06979', 'Xã Đạp Thanh', NULL, 'Xã', '202');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06982', 'Xã Nam Sơn', NULL, 'Xã', '202');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06985', 'Xã Lương Minh', NULL, 'Xã', '202');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06988', 'Xã Đồn Đạc', NULL, 'Xã', '202');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06994', 'Thị trấn Cái Rồng', NULL, 'Thị trấn', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('06997', 'Xã Đài Xuyên', NULL, 'Xã', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07000', 'Xã Bình Dân', NULL, 'Xã', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07003', 'Xã Vạn Yên', NULL, 'Xã', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07006', 'Xã Minh Châu', NULL, 'Xã', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07009', 'Xã Đoàn Kết', NULL, 'Xã', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07012', 'Xã Hạ Long', NULL, 'Xã', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07015', 'Xã Đông Xá', NULL, 'Xã', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07018', 'Xã Bản Sen', NULL, 'Xã', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07021', 'Xã Thắng Lợi', NULL, 'Xã', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07024', 'Xã Quan Lạn', NULL, 'Xã', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07027', 'Xã Ngọc Vừng', NULL, 'Xã', '203');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07069', 'Phường Mạo Khê', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07075', 'Xã An Sinh', NULL, 'Xã', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07078', 'Xã Tràng Lương', NULL, 'Xã', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07081', 'Phường Bình Khê', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07084', 'Xã Việt Dân', NULL, 'Xã', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07090', 'Phường Bình Dương', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07093', 'Phường Đức Chính', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07096', 'Phường Tràng An', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07099', 'Xã Nguyễn Huệ', NULL, 'Xã', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07102', 'Phường Thủy An', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07105', 'Phường Xuân Sơn', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07108', 'Xã Hồng Thái Tây', NULL, 'Xã', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07111', 'Xã Hồng Thái Đông', NULL, 'Xã', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07114', 'Phường Hoàng Quế', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07117', 'Phường Yên Thọ', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07120', 'Phường Hồng Phong', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07123', 'Phường Kim Sơn', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07126', 'Phường Hưng Đạo', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07129', 'Phường Yên Đức', NULL, 'Phường', '205');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07132', 'Phường Quảng Yên', NULL, 'Phường', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07135', 'Phường Đông Mai', NULL, 'Phường', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07138', 'Phường Minh Thành', NULL, 'Phường', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07144', 'Xã Sông Khoai', NULL, 'Xã', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07147', 'Xã Hiệp Hòa', NULL, 'Xã', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07150', 'Phường Cộng Hòa', NULL, 'Phường', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07153', 'Xã Tiền An', NULL, 'Xã', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07156', 'Xã Hoàng Tân', NULL, 'Xã', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07159', 'Phường Tân An', NULL, 'Phường', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07162', 'Phường Yên Giang', NULL, 'Phường', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07165', 'Phường Nam Hoà', NULL, 'Phường', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07168', 'Phường Hà An', NULL, 'Phường', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07171', 'Xã Cẩm La', NULL, 'Xã', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07174', 'Phường Phong Hải', NULL, 'Phường', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07177', 'Phường Yên Hải', NULL, 'Phường', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07180', 'Xã Liên Hòa', NULL, 'Xã', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07183', 'Phường Phong Cốc', NULL, 'Phường', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07186', 'Xã Liên Vị', NULL, 'Xã', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07189', 'Xã Tiền Phong', NULL, 'Xã', '206');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07192', 'Thị trấn Cô Tô', NULL, 'Thị trấn', '207');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07195', 'Xã Đồng Tiến', NULL, 'Xã', '207');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07198', 'Xã Thanh Lân', NULL, 'Xã', '207');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07201', 'Phường Thọ Xương', NULL, 'Phường', '213');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07204', 'Phường Trần Nguyên Hãn', NULL, 'Phường', '213');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07207', 'Phường Ngô Quyền', NULL, 'Phường', '213');
INSERT INTO Phuong_Xa (Ma_PX, Ten_PX, Ten_Tieng_Anh, Cap, Ma_QH)
VALUES ('07210', 'Phường Hoàng Văn Thụ', NULL, 'Phường', '213');