INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('1', 'Quận Ba Đình', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('2', 'Quận Hoàn Kiếm', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('3', 'Quận Tây Hồ', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('4', 'Quận Long Biên', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('5', 'Quận Cầu Giấy', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('6', 'Quận Đống Đa', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('7', 'Quận Hai Bà Trưng', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('8', 'Quận Hoàng Mai', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('9', 'Quận Thanh Xuân', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('16', 'Huyện Sóc Sơn', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('17', 'Huyện Đông Anh', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('18', 'Huyện Gia Lâm', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('19', 'Quận Nam Từ Liêm', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('20', 'Huyện Thanh Trì', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('21', 'Quận Bắc Từ Liêm', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('250', 'Huyện Mê Linh', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('268', 'Quận Hà Đông', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('269', 'Thị xã Sơn Tây', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('271', 'Huyện Ba Vì', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('272', 'Huyện Phúc Thọ', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('273', 'Huyện Đan Phượng', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('274', 'Huyện Hoài Đức', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('275', 'Huyện Quốc Oai', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('276', 'Huyện Thạch Thất', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('277', 'Huyện Chương Mỹ', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('278', 'Huyện Thanh Oai', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('279', 'Huyện Thường Tín', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('280', 'Huyện Phú Xuyên', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('281', 'Huyện Ứng Hòa', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('282', 'Huyện Mỹ Đức', '1');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('24', 'Thành phố Hà Giang', '2');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('26', 'Huyện Đồng Văn', '2');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('27', 'Huyện Mèo Vạc', '2');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('28', 'Huyện Yên Minh', '2');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('29', 'Huyện Quản Bạ', '2');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('30', 'Huyện Vị Xuyên', '2');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('31', 'Huyện Bắc Mê', '2');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('32', 'Huyện Hoàng Su Phì', '2');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('33', 'Huyện Xín Mần', '2');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('34', 'Huyện Bắc Quang', '2');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('35', 'Huyện Quang Bình', '2');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('40', 'Thành phố Cao Bằng', '4');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('42', 'Huyện Bảo Lâm', '4');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('43', 'Huyện Bảo Lạc', '4');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('45', 'Huyện Hà Quảng', '4');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('47', 'Huyện Trùng Khánh', '4');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('48', 'Huyện Hạ Lang', '4');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('49', 'Huyện Quảng Hòa', '4');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('51', 'Huyện Hoà An', '4');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('52', 'Huyện Nguyên Bình', '4');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('53', 'Huyện Thạch An', '4');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('58', 'Thành Phố Bắc Kạn', '6');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('60', 'Huyện Pác Nặm', '6');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('61', 'Huyện Ba Bể', '6');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('62', 'Huyện Ngân Sơn', '6');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('63', 'Huyện Bạch Thông', '6');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('64', 'Huyện Chợ Đồn', '6');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('65', 'Huyện Chợ Mới', '6');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('66', 'Huyện Na Rì', '6');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('70', 'Thành phố Tuyên Quang', '8');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('71', 'Huyện Lâm Bình', '8');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('72', 'Huyện Na Hang', '8');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('73', 'Huyện Chiêm Hóa', '8');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('74', 'Huyện Hàm Yên', '8');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('75', 'Huyện Yên Sơn', '8');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('76', 'Huyện Sơn Dương', '8');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('80', 'Thành phố Lào Cai', '10');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('82', 'Huyện Bát Xát', '10');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('83', 'Huyện Mường Khương', '10');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('84', 'Huyện Si Ma Cai', '10');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('85', 'Huyện Bắc Hà', '10');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('86', 'Huyện Bảo Thắng', '10');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('87', 'Huyện Bảo Yên', '10');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('88', 'Thị xã Sa Pa', '10');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('89', 'Huyện Văn Bàn', '10');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('94', 'Thành phố Điện Biên Phủ', '11');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('95', 'Thị Xã Mường Lay', '11');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('96', 'Huyện Mường Nhé', '11');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('97', 'Huyện Mường Chà', '11');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('98', 'Huyện Tủa Chùa', '11');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('99', 'Huyện Tuần Giáo', '11');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('100', 'Huyện Điện Biên', '11');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('101', 'Huyện Điện Biên Đông', '11');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('102', 'Huyện Mường Ảng', '11');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('103', 'Huyện Nậm Pồ', '11');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('105', 'Thành phố Lai Châu', '12');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('106', 'Huyện Tam Đường', '12');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('107', 'Huyện Mường Tè', '12');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('108', 'Huyện Sìn Hồ', '12');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('109', 'Huyện Phong Thổ', '12');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('110', 'Huyện Than Uyên', '12');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('111', 'Huyện Tân Uyên', '12');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('112', 'Huyện Nậm Nhùn', '12');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('116', 'Thành phố Sơn La', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('118', 'Huyện Quỳnh Nhai', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('119', 'Huyện Thuận Châu', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('120', 'Huyện Mường La', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('121', 'Huyện Bắc Yên', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('122', 'Huyện Phù Yên', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('123', 'Huyện Mộc Châu', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('124', 'Huyện Yên Châu', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('125', 'Huyện Mai Sơn', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('126', 'Huyện Sông Mã', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('127', 'Huyện Sốp Cộp', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('128', 'Huyện Vân Hồ', '14');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('132', 'Thành phố Yên Bái', '15');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('133', 'Thị xã Nghĩa Lộ', '15');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('135', 'Huyện Lục Yên', '15');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('136', 'Huyện Văn Yên', '15');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('137', 'Huyện Mù Căng Chải', '15');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('138', 'Huyện Trấn Yên', '15');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('139', 'Huyện Trạm Tấu', '15');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('140', 'Huyện Văn Chấn', '15');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('141', 'Huyện Yên Bình', '15');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('148', 'Thành phố Hòa Bình', '17');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('150', 'Huyện Đà Bắc', '17');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('152', 'Huyện Lương Sơn', '17');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('153', 'Huyện Kim Bôi', '17');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('154', 'Huyện Cao Phong', '17');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('155', 'Huyện Tân Lạc', '17');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('156', 'Huyện Mai Châu', '17');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('157', 'Huyện Lạc Sơn', '17');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('158', 'Huyện Yên Thủy', '17');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('159', 'Huyện Lạc Thủy', '17');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('164', 'Thành phố Thái Nguyên', '19');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('165', 'Thành phố Sông Công', '19');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('167', 'Huyện Định Hóa', '19');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('168', 'Huyện Phú Lương', '19');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('169', 'Huyện Đồng Hỷ', '19');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('170', 'Huyện Võ Nhai', '19');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('171', 'Huyện Đại Từ', '19');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('172', 'Thành phố Phổ Yên', '19');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('173', 'Huyện Phú Bình', '19');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('178', 'Thành phố Lạng Sơn', '20');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('180', 'Huyện Tràng Định', '20');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('181', 'Huyện Bình Gia', '20');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('182', 'Huyện Văn Lãng', '20');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('183', 'Huyện Cao Lộc', '20');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('184', 'Huyện Văn Quan', '20');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('185', 'Huyện Bắc Sơn', '20');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('186', 'Huyện Hữu Lũng', '20');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('187', 'Huyện Chi Lăng', '20');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('188', 'Huyện Lộc Bình', '20');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('189', 'Huyện Đình Lập', '20');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('193', 'Thành phố Hạ Long', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('194', 'Thành phố Móng Cái', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('195', 'Thành phố Cẩm Phả', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('196', 'Thành phố Uông Bí', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('198', 'Huyện Bình Liêu', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('199', 'Huyện Tiên Yên', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('200', 'Huyện Đầm Hà', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('201', 'Huyện Hải Hà', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('202', 'Huyện Ba Chẽ', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('203', 'Huyện Vân Đồn', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('205', 'Thành phố Đông Triều', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('206', 'Thị xã Quảng Yên', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('207', 'Huyện Cô Tô', '22');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('213', 'Thành phố Bắc Giang', '24');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('215', 'Huyện Yên Thế', '24');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('216', 'Huyện Tân Yên', '24');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('217', 'Huyện Lạng Giang', '24');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('218', 'Huyện Lục Nam', '24');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('219', 'Huyện Lục Ngạn', '24');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('220', 'Huyện Sơn Động', '24');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('221', 'Huyện Yên Dũng', '24');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('222', 'Thị Xã Việt Yên', '24');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('223', 'Huyện Hiệp Hòa', '24');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('227', 'Thành phố Việt Trì', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('228', 'Thị xã Phú Thọ', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('230', 'Huyện Đoan Hùng', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('231', 'Huyện Hạ Hoà', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('232', 'Huyện Thanh Ba', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('233', 'Huyện Phù Ninh', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('234', 'Huyện Yên Lập', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('235', 'Huyện Cẩm Khê', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('236', 'Huyện Tam Nông', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('237', 'Huyện Lâm Thao', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('238', 'Huyện Thanh Sơn', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('239', 'Huyện Thanh Thuỷ', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('240', 'Huyện Tân Sơn', '25');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('243', 'Thành phố Vĩnh Yên', '26');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('244', 'Thành phố Phúc Yên', '26');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('246', 'Huyện Lập Thạch', '26');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('247', 'Huyện Tam Dương', '26');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('248', 'Huyện Tam Đảo', '26');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('249', 'Huyện Bình Xuyên', '26');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('251', 'Huyện Yên Lạc', '26');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('252', 'Huyện Vĩnh Tường', '26');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('253', 'Huyện Sông Lô', '26');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('256', 'Thành phố Bắc Ninh', '27');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('258', 'Huyện Yên Phong', '27');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('259', 'Thị xã Quế Võ', '27');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('260', 'Huyện Tiên Du', '27');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('261', 'Thành phố Từ Sơn', '27');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('262', 'Thị xã Thuận Thành', '27');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('263', 'Huyện Gia Bình', '27');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('264', 'Huyện Lương Tài', '27');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('288', 'Thành phố Hải Dương', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('290', 'Thành phố Chí Linh', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('291', 'Huyện Nam Sách', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('292', 'Thị xã Kinh Môn', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('293', 'Huyện Kim Thành', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('294', 'Huyện Thanh Hà', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('295', 'Huyện Cẩm Giàng', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('296', 'Huyện Bình Giang', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('297', 'Huyện Gia Lộc', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('298', 'Huyện Tứ Kỳ', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('299', 'Huyện Ninh Giang', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('300', 'Huyện Thanh Miện', '30');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('303', 'Quận Hồng Bàng', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('304', 'Quận Ngô Quyền', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('305', 'Quận Lê Chân', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('306', 'Quận Hải An', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('307', 'Quận Kiến An', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('308', 'Quận Đồ Sơn', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('309', 'Quận Dương Kinh', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('311', 'Thành phố Thuỷ Nguyên', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('312', 'Quận An Dương', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('313', 'Huyện An Lão', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('314', 'Huyện Kiến Thuỵ', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('315', 'Huyện Tiên Lãng', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('316', 'Huyện Vĩnh Bảo', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('317', 'Huyện Cát Hải', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('318', 'Huyện Bạch Long Vĩ', '31');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('323', 'Thành phố Hưng Yên', '33');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('325', 'Huyện Văn Lâm', '33');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('326', 'Huyện Văn Giang', '33');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('327', 'Huyện Yên Mỹ', '33');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('328', 'Thị xã Mỹ Hào', '33');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('329', 'Huyện Ân Thi', '33');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('330', 'Huyện Khoái Châu', '33');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('331', 'Huyện Kim Động', '33');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('332', 'Huyện Tiên Lữ', '33');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('333', 'Huyện Phù Cừ', '33');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('336', 'Thành phố Thái Bình', '34');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('338', 'Huyện Quỳnh Phụ', '34');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('339', 'Huyện Hưng Hà', '34');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('340', 'Huyện Đông Hưng', '34');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('341', 'Huyện Thái Thụy', '34');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('342', 'Huyện Tiền Hải', '34');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('343', 'Huyện Kiến Xương', '34');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('344', 'Huyện Vũ Thư', '34');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('347', 'Thành phố Phủ Lý', '35');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('349', 'Thị xã Duy Tiên', '35');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('350', 'Huyện Kim Bảng', '35');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('351', 'Huyện Thanh Liêm', '35');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('352', 'Huyện Bình Lục', '35');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('353', 'Huyện Lý Nhân', '35');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('356', 'Thành phố Nam Định', '36');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('359', 'Huyện Vụ Bản', '36');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('360', 'Huyện Ý Yên', '36');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('361', 'Huyện Nghĩa Hưng', '36');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('362', 'Huyện Nam Trực', '36');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('363', 'Huyện Trực Ninh', '36');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('364', 'Huyện Xuân Trường', '36');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('365', 'Huyện Giao Thủy', '36');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('366', 'Huyện Hải Hậu', '36');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('369', 'Thành phố Ninh Bình', '37');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('370', 'Thành phố Tam Điệp', '37');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('372', 'Huyện Nho Quan', '37');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('373', 'Huyện Gia Viễn', '37');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('374', 'Huyện Hoa Lư', '37');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('375', 'Huyện Yên Khánh', '37');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('376', 'Huyện Kim Sơn', '37');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('377', 'Huyện Yên Mô', '37');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('380', 'Thành phố Thanh Hóa', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('381', 'Thị xã Bỉm Sơn', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('382', 'Thành phố Sầm Sơn', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('384', 'Huyện Mường Lát', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('385', 'Huyện Quan Hóa', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('386', 'Huyện Bá Thước', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('387', 'Huyện Quan Sơn', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('388', 'Huyện Lang Chánh', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('389', 'Huyện Ngọc Lặc', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('390', 'Huyện Cẩm Thủy', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('391', 'Huyện Thạch Thành', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('392', 'Huyện Hà Trung', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('393', 'Huyện Vĩnh Lộc', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('394', 'Huyện Yên Định', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('395', 'Huyện Thọ Xuân', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('396', 'Huyện Thường Xuân', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('397', 'Huyện Triệu Sơn', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('398', 'Huyện Thiệu Hóa', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('399', 'Huyện Hoằng Hóa', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('400', 'Huyện Hậu Lộc', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('401', 'Huyện Nga Sơn', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('402', 'Huyện Như Xuân', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('403', 'Huyện Như Thanh', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('404', 'Huyện Nông Cống', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('405', 'Huyện Đông Sơn', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('406', 'Huyện Quảng Xương', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('407', 'Thị xã Nghi Sơn', '38');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('412', 'Thành phố Vinh', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('414', 'Thị xã Thái Hoà', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('415', 'Huyện Quế Phong', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('416', 'Huyện Quỳ Châu', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('417', 'Huyện Kỳ Sơn', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('418', 'Huyện Tương Dương', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('419', 'Huyện Nghĩa Đàn', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('420', 'Huyện Quỳ Hợp', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('421', 'Huyện Quỳnh Lưu', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('422', 'Huyện Con Cuông', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('423', 'Huyện Tân Kỳ', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('424', 'Huyện Anh Sơn', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('425', 'Huyện Diễn Châu', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('426', 'Huyện Yên Thành', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('427', 'Huyện Đô Lương', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('428', 'Huyện Thanh Chương', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('429', 'Huyện Nghi Lộc', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('430', 'Huyện Nam Đàn', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('431', 'Huyện Hưng Nguyên', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('432', 'Thị xã Hoàng Mai', '40');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('436', 'Thành phố Hà Tĩnh', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('437', 'Thị xã Hồng Lĩnh', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('439', 'Huyện Hương Sơn', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('440', 'Huyện Đức Thọ', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('441', 'Huyện Vũ Quang', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('442', 'Huyện Nghi Xuân', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('443', 'Huyện Can Lộc', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('444', 'Huyện Hương Khê', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('445', 'Huyện Thạch Hà', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('446', 'Huyện Cẩm Xuyên', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('447', 'Huyện Kỳ Anh', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('448', 'Huyện Lộc Hà', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('449', 'Thị xã Kỳ Anh', '42');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('450', 'Thành Phố Đồng Hới', '44');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('452', 'Huyện Minh Hóa', '44');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('453', 'Huyện Tuyên Hóa', '44');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('454', 'Huyện Quảng Trạch', '44');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('455', 'Huyện Bố Trạch', '44');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('456', 'Huyện Quảng Ninh', '44');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('457', 'Huyện Lệ Thủy', '44');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('458', 'Thị xã Ba Đồn', '44');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('461', 'Thành phố Đông Hà', '45');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('462', 'Thị xã Quảng Trị', '45');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('464', 'Huyện Vĩnh Linh', '45');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('465', 'Huyện Hướng Hóa', '45');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('466', 'Huyện Gio Linh', '45');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('467', 'Huyện Đa Krông', '45');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('468', 'Huyện Cam Lộ', '45');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('469', 'Huyện Triệu Phong', '45');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('470', 'Huyện Hải Lăng', '45');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('471', 'Huyện Cồn Cỏ', '45');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('474', 'Quận Thuận Hóa', '46');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('476', 'Thị xã Phong Điền', '46');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('477', 'Huyện Quảng Điền', '46');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('478', 'Huyện Phú Vang', '46');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('479', 'Thị xã Hương Thủy', '46');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('480', 'Thị xã Hương Trà', '46');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('481', 'Huyện A Lưới', '46');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('482', 'Huyện Phú Lộc', '46');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('483', 'Huyện Nam Đông', '46');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('490', 'Quận Liên Chiểu', '48');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('491', 'Quận Thanh Khê', '48');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('492', 'Quận Hải Châu', '48');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('493', 'Quận Sơn Trà', '48');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('494', 'Quận Ngũ Hành Sơn', '48');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('495', 'Quận Cẩm Lệ', '48');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('497', 'Huyện Hòa Vang', '48');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('498', 'Huyện Hoàng Sa', '48');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('502', 'Thành phố Tam Kỳ', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('503', 'Thành phố Hội An', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('504', 'Huyện Tây Giang', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('505', 'Huyện Đông Giang', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('506', 'Huyện Đại Lộc', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('507', 'Thị xã Điện Bàn', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('508', 'Huyện Duy Xuyên', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('509', 'Huyện Quế Sơn', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('510', 'Huyện Nam Giang', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('511', 'Huyện Phước Sơn', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('512', 'Huyện Hiệp Đức', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('513', 'Huyện Thăng Bình', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('514', 'Huyện Tiên Phước', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('515', 'Huyện Bắc Trà My', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('516', 'Huyện Nam Trà My', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('517', 'Huyện Núi Thành', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('518', 'Huyện Phú Ninh', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('519', 'Huyện Nông Sơn', '49');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('522', 'Thành phố Quảng Ngãi', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('524', 'Huyện Bình Sơn', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('525', 'Huyện Trà Bồng', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('527', 'Huyện Sơn Tịnh', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('528', 'Huyện Tư Nghĩa', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('529', 'Huyện Sơn Hà', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('530', 'Huyện Sơn Tây', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('531', 'Huyện Minh Long', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('532', 'Huyện Nghĩa Hành', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('533', 'Huyện Mộ Đức', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('534', 'Thị xã Đức Phổ', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('535', 'Huyện Ba Tơ', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('536', 'Huyện Lý Sơn', '51');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('540', 'Thành phố Quy Nhơn', '52');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('542', 'Huyện An Lão', '52');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('543', 'Thị xã Hoài Nhơn', '52');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('544', 'Huyện Hoài Ân', '52');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('545', 'Huyện Phù Mỹ', '52');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('546', 'Huyện Vĩnh Thạnh', '52');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('547', 'Huyện Tây Sơn', '52');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('548', 'Huyện Phù Cát', '52');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('549', 'Thị xã An Nhơn', '52');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('550', 'Huyện Tuy Phước', '52');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('551', 'Huyện Vân Canh', '52');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('555', 'Thành phố Tuy Hoà', '54');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('557', 'Thị xã Sông Cầu', '54');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('558', 'Huyện Đồng Xuân', '54');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('559', 'Huyện Tuy An', '54');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('560', 'Huyện Sơn Hòa', '54');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('561', 'Huyện Sông Hinh', '54');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('562', 'Huyện Tây Hoà', '54');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('563', 'Huyện Phú Hoà', '54');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('564', 'Thị xã Đông Hòa', '54');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('568', 'Thành phố Nha Trang', '56');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('569', 'Thành phố Cam Ranh', '56');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('570', 'Huyện Cam Lâm', '56');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('571', 'Huyện Vạn Ninh', '56');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('572', 'Thị xã Ninh Hòa', '56');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('573', 'Huyện Khánh Vĩnh', '56');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('574', 'Huyện Diên Khánh', '56');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('575', 'Huyện Khánh Sơn', '56');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('576', 'Huyện Trường Sa', '56');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('582', 'Thành phố Phan Rang-Tháp Chàm', '58');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('584', 'Huyện Bác Ái', '58');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('585', 'Huyện Ninh Sơn', '58');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('586', 'Huyện Ninh Hải', '58');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('587', 'Huyện Ninh Phước', '58');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('588', 'Huyện Thuận Bắc', '58');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('589', 'Huyện Thuận Nam', '58');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('593', 'Thành phố Phan Thiết', '60');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('594', 'Thị xã La Gi', '60');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('595', 'Huyện Tuy Phong', '60');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('596', 'Huyện Bắc Bình', '60');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('597', 'Huyện Hàm Thuận Bắc', '60');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('598', 'Huyện Hàm Thuận Nam', '60');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('599', 'Huyện Tánh Linh', '60');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('600', 'Huyện Đức Linh', '60');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('601', 'Huyện Hàm Tân', '60');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('602', 'Huyện Phú Quí', '60');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('608', 'Thành phố Kon Tum', '62');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('610', 'Huyện Đắk Glei', '62');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('611', 'Huyện Ngọc Hồi', '62');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('612', 'Huyện Đắk Tô', '62');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('613', 'Huyện Kon Plông', '62');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('614', 'Huyện Kon Rẫy', '62');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('615', 'Huyện Đắk Hà', '62');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('616', 'Huyện Sa Thầy', '62');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('617', 'Huyện Tu Mơ Rông', '62');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('618', 'Huyện Ia H Drai', '62');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('622', 'Thành phố Pleiku', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('623', 'Thị xã An Khê', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('624', 'Thị xã Ayun Pa', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('625', 'Huyện KBang', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('626', 'Huyện Đăk Đoa', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('627', 'Huyện Chư Păh', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('628', 'Huyện Ia Grai', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('629', 'Huyện Mang Yang', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('630', 'Huyện Kông Chro', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('631', 'Huyện Đức Cơ', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('632', 'Huyện Chư Prông', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('633', 'Huyện Chư Sê', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('634', 'Huyện Đăk Pơ', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('635', 'Huyện Ia Pa', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('637', 'Huyện Krông Pa', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('638', 'Huyện Phú Thiện', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('639', 'Huyện Chư Pưh', '64');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('643', 'Thành phố Buôn Ma Thuột', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('644', 'Thị Xã Buôn Hồ', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('645', 'Huyện Ea H leo', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('646', 'Huyện Ea Súp', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('647', 'Huyện Buôn Đôn', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('648', 'Huyện Cư M gar', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('649', 'Huyện Krông Búk', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('650', 'Huyện Krông Năng', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('651', 'Huyện Ea Kar', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('652', 'Huyện M Đrắk', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('653', 'Huyện Krông Bông', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('654', 'Huyện Krông Pắc', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('655', 'Huyện Krông A Na', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('656', 'Huyện Lắk', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('657', 'Huyện Cư Kuin', '66');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('660', 'Thành phố Gia Nghĩa', '67');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('661', 'Huyện Đăk Glong', '67');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('662', 'Huyện Cư Jút', '67');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('663', 'Huyện Đắk Mil', '67');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('664', 'Huyện Krông Nô', '67');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('665', 'Huyện Đắk Song', '67');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('666', 'Huyện Đắk RLấp', '67');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('667', 'Huyện Tuy Đức', '67');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('672', 'Thành phố Đà Lạt', '68');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('673', 'Thành phố Bảo Lộc', '68');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('674', 'Huyện Đam Rông', '68');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('675', 'Huyện Lạc Dương', '68');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('676', 'Huyện Lâm Hà', '68');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('677', 'Huyện Đơn Dương', '68');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('678', 'Huyện Đức Trọng', '68');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('679', 'Huyện Di Linh', '68');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('680', 'Huyện Bảo Lâm', '68');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('682', 'Huyện Đạ Huoai', '68');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('688', 'Thị xã Phước Long', '70');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('689', 'Thành phố Đồng Xoài', '70');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('690', 'Thị xã Bình Long', '70');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('691', 'Huyện Bù Gia Mập', '70');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('692', 'Huyện Lộc Ninh', '70');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('693', 'Huyện Bù Đốp', '70');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('694', 'Huyện Hớn Quản', '70');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('695', 'Huyện Đồng Phú', '70');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('696', 'Huyện Bù Đăng', '70');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('697', 'Thị xã Chơn Thành', '70');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('698', 'Huyện Phú Riềng', '70');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('703', 'Thành phố Tây Ninh', '72');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('705', 'Huyện Tân Biên', '72');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('706', 'Huyện Tân Châu', '72');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('707', 'Huyện Dương Minh Châu', '72');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('708', 'Huyện Châu Thành', '72');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('709', 'Thị xã Hòa Thành', '72');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('710', 'Huyện Gò Dầu', '72');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('711', 'Huyện Bến Cầu', '72');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('712', 'Thị xã Trảng Bàng', '72');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('718', 'Thành phố Thủ Dầu Một', '74');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('719', 'Huyện Bàu Bàng', '74');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('720', 'Huyện Dầu Tiếng', '74');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('721', 'Thành phố Bến Cát', '74');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('722', 'Huyện Phú Giáo', '74');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('723', 'Thành phố Tân Uyên', '74');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('724', 'Thành phố Dĩ An', '74');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('725', 'Thành phố Thuận An', '74');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('726', 'Huyện Bắc Tân Uyên', '74');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('731', 'Thành phố Biên Hòa', '75');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('732', 'Thành phố Long Khánh', '75');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('734', 'Huyện Tân Phú', '75');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('735', 'Huyện Vĩnh Cửu', '75');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('736', 'Huyện Định Quán', '75');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('737', 'Huyện Trảng Bom', '75');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('738', 'Huyện Thống Nhất', '75');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('739', 'Huyện Cẩm Mỹ', '75');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('740', 'Huyện Long Thành', '75');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('741', 'Huyện Xuân Lộc', '75');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('742', 'Huyện Nhơn Trạch', '75');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('747', 'Thành phố Vũng Tàu', '77');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('748', 'Thành phố Bà Rịa', '77');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('750', 'Huyện Châu Đức', '77');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('751', 'Huyện Xuyên Mộc', '77');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('752', 'Huyện Long Điền', '77');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('753', 'Huyện Long Đất', '77');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('754', 'Thị xã Phú Mỹ', '77');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('755', 'Huyện Côn Đảo', '77');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('760', 'Quận 1', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('761', 'Quận 12', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('764', 'Quận Gò Vấp', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('765', 'Quận Bình Thạnh', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('766', 'Quận Tân Bình', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('767', 'Quận Tân Phú', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('768', 'Quận Phú Nhuận', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('769', 'Thành phố Thủ Đức', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('770', 'Quận 3', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('771', 'Quận 10', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('772', 'Quận 11', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('773', 'Quận 4', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('774', 'Quận 5', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('775', 'Quận 6', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('776', 'Quận 8', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('777', 'Quận Bình Tân', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('778', 'Quận 7', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('783', 'Huyện Củ Chi', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('784', 'Huyện Hóc Môn', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('785', 'Huyện Bình Chánh', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('786', 'Huyện Nhà Bè', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('787', 'Huyện Cần Giờ', '79');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('794', 'Thành phố Tân An', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('795', 'Thị xã Kiến Tường', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('796', 'Huyện Tân Hưng', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('797', 'Huyện Vĩnh Hưng', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('798', 'Huyện Mộc Hóa', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('799', 'Huyện Tân Thạnh', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('800', 'Huyện Thạnh Hóa', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('801', 'Huyện Đức Huệ', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('802', 'Huyện Đức Hòa', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('803', 'Huyện Bến Lức', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('804', 'Huyện Thủ Thừa', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('805', 'Huyện Tân Trụ', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('806', 'Huyện Cần Đước', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('807', 'Huyện Cần Giuộc', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('808', 'Huyện Châu Thành', '80');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('815', 'Thành phố Mỹ Tho', '82');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('816', 'Thành phố Gò Công', '82');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('817', 'Thị xã Cai Lậy', '82');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('818', 'Huyện Tân Phước', '82');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('819', 'Huyện Cái Bè', '82');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('820', 'Huyện Cai Lậy', '82');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('821', 'Huyện Châu Thành', '82');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('822', 'Huyện Chợ Gạo', '82');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('823', 'Huyện Gò Công Tây', '82');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('824', 'Huyện Gò Công Đông', '82');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('825', 'Huyện Tân Phú Đông', '82');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('829', 'Thành phố Bến Tre', '83');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('831', 'Huyện Châu Thành', '83');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('832', 'Huyện Chợ Lách', '83');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('833', 'Huyện Mỏ Cày Nam', '83');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('834', 'Huyện Giồng Trôm', '83');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('835', 'Huyện Bình Đại', '83');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('836', 'Huyện Ba Tri', '83');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('837', 'Huyện Thạnh Phú', '83');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('838', 'Huyện Mỏ Cày Bắc', '83');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('842', 'Thành phố Trà Vinh', '84');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('844', 'Huyện Càng Long', '84');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('845', 'Huyện Cầu Kè', '84');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('846', 'Huyện Tiểu Cần', '84');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('847', 'Huyện Châu Thành', '84');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('848', 'Huyện Cầu Ngang', '84');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('849', 'Huyện Trà Cú', '84');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('850', 'Huyện Duyên Hải', '84');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('851', 'Thị xã Duyên Hải', '84');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('855', 'Thành phố Vĩnh Long', '86');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('857', 'Huyện Long Hồ', '86');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('858', 'Huyện Mang Thít', '86');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('859', 'Huyện  Vũng Liêm', '86');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('860', 'Huyện Tam Bình', '86');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('861', 'Thị xã Bình Minh', '86');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('862', 'Huyện Trà Ôn', '86');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('863', 'Huyện Bình Tân', '86');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('866', 'Thành phố Cao Lãnh', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('867', 'Thành phố Sa Đéc', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('868', 'Thành phố Hồng Ngự', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('869', 'Huyện Tân Hồng', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('870', 'Huyện Hồng Ngự', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('871', 'Huyện Tam Nông', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('872', 'Huyện Tháp Mười', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('873', 'Huyện Cao Lãnh', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('874', 'Huyện Thanh Bình', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('875', 'Huyện Lấp Vò', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('876', 'Huyện Lai Vung', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('877', 'Huyện Châu Thành', '87');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('883', 'Thành phố Long Xuyên', '89');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('884', 'Thành phố Châu Đốc', '89');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('886', 'Huyện An Phú', '89');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('887', 'Thị xã Tân Châu', '89');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('888', 'Huyện Phú Tân', '89');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('889', 'Huyện Châu Phú', '89');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('890', 'Thị xã Tịnh Biên', '89');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('891', 'Huyện Tri Tôn', '89');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('892', 'Huyện Châu Thành', '89');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('893', 'Huyện Chợ Mới', '89');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('894', 'Huyện Thoại Sơn', '89');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('899', 'Thành phố Rạch Giá', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('900', 'Thành phố Hà Tiên', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('902', 'Huyện Kiên Lương', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('903', 'Huyện Hòn Đất', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('904', 'Huyện Tân Hiệp', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('905', 'Huyện Châu Thành', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('906', 'Huyện Giồng Riềng', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('907', 'Huyện Gò Quao', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('908', 'Huyện An Biên', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('909', 'Huyện An Minh', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('910', 'Huyện Vĩnh Thuận', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('911', 'Thành phố Phú Quốc', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('912', 'Huyện Kiên Hải', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('913', 'Huyện U Minh Thượng', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('914', 'Huyện Giang Thành', '91');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('916', 'Quận Ninh Kiều', '92');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('917', 'Quận Ô Môn', '92');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('918', 'Quận Bình Thuỷ', '92');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('919', 'Quận Cái Răng', '92');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('923', 'Quận Thốt Nốt', '92');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('924', 'Huyện Vĩnh Thạnh', '92');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('925', 'Huyện Cờ Đỏ', '92');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('926', 'Huyện Phong Điền', '92');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('927', 'Huyện Thới Lai', '92');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('930', 'Thành phố Vị Thanh', '93');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('931', 'Thành phố Ngã Bảy', '93');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('932', 'Huyện Châu Thành A', '93');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('933', 'Huyện Châu Thành', '93');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('934', 'Huyện Phụng Hiệp', '93');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('935', 'Huyện Vị Thuỷ', '93');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('936', 'Huyện Long Mỹ', '93');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('937', 'Thị xã Long Mỹ', '93');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('941', 'Thành phố Sóc Trăng', '94');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('942', 'Huyện Châu Thành', '94');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('943', 'Huyện Kế Sách', '94');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('944', 'Huyện Mỹ Tú', '94');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('945', 'Huyện Cù Lao Dung', '94');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('946', 'Huyện Long Phú', '94');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('947', 'Huyện Mỹ Xuyên', '94');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('948', 'Thị xã Ngã Năm', '94');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('949', 'Huyện Thạnh Trị', '94');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('950', 'Thị xã Vĩnh Châu', '94');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('951', 'Huyện Trần Đề', '94');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('954', 'Thành phố Bạc Liêu', '95');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('956', 'Huyện Hồng Dân', '95');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('957', 'Huyện Phước Long', '95');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('958', 'Huyện Vĩnh Lợi', '95');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('959', 'Thị xã Giá Rai', '95');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('960', 'Huyện Đông Hải', '95');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('961', 'Huyện Hoà Bình', '95');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('964', 'Thành phố Cà Mau', '96');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('966', 'Huyện U Minh', '96');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('967', 'Huyện Thới Bình', '96');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('968', 'Huyện Trần Văn Thời', '96');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('969', 'Huyện Cái Nước', '96');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('970', 'Huyện Đầm Dơi', '96');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('971', 'Huyện Năm Căn', '96');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('972', 'Huyện Phú Tân', '96');
INSERT INTO Quan_Huyen (Ma_QH, Ten_QH, Ma_TP) VALUES ('973', 'Huyện Ngọc Hiển', '96');